### ISSUE TITLE
Add filesystem wildcard matching to the file table

### ISSUE THREAD

**Issue by marpaia** [facebook/osquery#1013]
We should use the same code that we use for the filesystem monitoring code.

**Comment by theopolis** [comment]
It's not that easy since SQL applies predicate constraints after we introspect and act on the parsed expressions. If you say `path = "/Users/%/.ssh/%"` you can extract that wildcard expression, apply the globbing, and return the correct rows. SQL will step in and match your input equality expression against the mutated/parsed result and drop your rows.

There are a few paths forward:
- Add a new column that accepts a wildcard, something like `match` or `pattern` and return input patterns alongside the expanded result paths from the globbing.
- Expose the `LIKE` operator in predicate parsing (requires a bit of SQLite hacking)
- Interrupt the `=` operator in our sqlite modules to relax decision making. This is very challenging when multiplexing constraints and I'm 75% it's possible without SQLite modifications.

SQLite also has a trigger or "hidden" column concept that can be used for the first suggested path.

**Comment by marpaia** [comment]
I think that the first option, a new column that accepts a wildcard, is definitely the easiest path forward, although arguably the least favorable end-user experience.

**Comment by marpaia** [comment]
Closing this to track in #1038.

**Comment by theopolis** [comment]
Why are issues closed when PRs opened? Shouldn't the issue be closed automatically when the PR is merged if using the [fix...] title notation or manually otherwise. Closing the issue-discussion before the code lands seems incorrect. E.g., you don't close internal tasks when a diff is created, only after the code is reviewed and the implementation accepted. Consider what happens when the first or series of subsequent PRs are non-starts or eventually abandoned. The originating issue/discussion is good to keep around. :)

**Comment by marpaia** [comment]
We've been doing this for a while? Personally, I think closing open issues when you have a working PR in an effort to move all conversation to the code is a good way to make sure that conversations are implementation focused. That's at least my logic as to why I've been doing that for most of the history of the project.

Internally, tasks and diffs each have more individual conversation value. Nesting, creating dependencies, etc. are all things that allow you to use tasks to manage work that you have to do. We can't do ANY of that in GitHub issues.

Like I said, I think that closing an issue in favor of a PR encourages everyone involved to reason about the problem differently, as we can see from the comments that were on the Python API issue vs the Python API PR.

I agree that the originating discussion is good to keep around, as we can see by the conversation we're having now, it's not like old issues go anywhere when they're closed. If the PR is abandoned, we can always click the "Reopen" button?

**Comment by theopolis** [comment]
I think you're the only one closing issues before code lands. ;)

We have force fitted a lot of our internal workflow into GH, dependencies in issues and most of what tasks allow (the things you mention) work nicely. Reasoning about the code and the more generic issue, even very targeted bugs, should be separate. I've gotten a lot of value by keeping both open. There are quite a few times where the original code implementation is not the correct method or approach.

I've never seen another project close issues before code lands or the issues' concerns are resolved. Keeping an issue discussion open communicates that the project's developers and users are still debating implementation, tracking ideas, discussing affected uses and impact, among other things. A closed issue implies the topic is no longer on the project's roadmap. And deferring approaches and issue discussion to a PR seems rigid and awkward.

**Comment by theopolis** [comment]
If we don't mind waiting a weekend I think there's another potential approach. The xFiler/xBestIndex overloads do receive a note when a constraint with an invalid (unusable) operator is included. We can use that to "trial run" a filter, which causes xFindFunction and passes it a user data blob containing infix expressions. *I think* we can lash this together and restart the SQLite return context to bypass filtering logic AND operate on LIKE/GLOB/OR.
