### ISSUE TITLE
no memory utilization stats appearing in profile.py

### ISSUE THREAD

**Issue by shira27** [facebook/osquery#1081]
Hi,
In order to test the performance of the queries that we have I'm using the python script profile.py as described in the below documentation:
http://osquery.readthedocs.org/en/latest/deployment/performance-safety/#testing-query-performance

I'm running into issues when running this script as all the queries I have tried, show a memory and cpu usage as 0 by the script and it fails to run due to zero memory utilization. Increasing the count for number of times the query needs to be run does not change this memory usage as well. When trying to run the same query on a loop by using osqueryi on the command line, we are able to see the memory usage but the script profile.py only shows the usage as 0.

**Comment by theopolis** [comment]
You might be missing psutil? Can you try: `pip install -r requirements.txt`

**Comment by shira27** [comment]
Hi I do have psutil installed. Are the following required as well?:
Jinja2
argparse
pexpect
thrift

**Comment by marpaia** [comment]
pexpect, thrift and argparse are all required for tests. jinja2 is required for building osquery.

**Comment by shira27** [comment]
Hi , I get the same issue even after installing the requirements mentioned.
The current_stats values are as follows:
{u'memory': pextmem(rss=0, vms=0, shared=0, text=0, lib=0, data=0, dirty=0), u'fds': 0, u'counters': pio(read_count=43, write_count=7, read_bytes=0, write_bytes=0), u'cpu_times': pcputimes(user=0.0, system=0.0), u'utilization': 0.0}

**Comment by marpaia** [comment]
@shira27 what operating system is this occurring on?

**Comment by shira27** [comment]
I apologize for the delay in getting back. Its on RHEL 6.4

**Comment by marpaia** [comment]
Ah, interesting. We have cursory support for RHEL 6.5 (it's currently failing right now, @javuto knows more). We don't "support" anything working on RHEL 6.4, so we don't have any infrastructure set up to help you debug, unfortunately. 

In order to be pragmatic about the amount of time we spend debugging miscellaneous issues on disparate platforms, we only ensure that our build and tools work with the operating systems that we have vagrant virtual infrastructure setup for (https://github.com/facebook/osquery/blob/master/Vagrantfile). 

If supporting RHEL 6.4 is something that you'd like to help out with, we'd love the help. @wxsBSD and @zi0r generously added FreeBSD support recently, so there's definitely precedent for adding support for new operating systems.

I'm going to close this because of the above.
