### ISSUE TITLE
Upgrade Yara to 3.4.0

### ISSUE THREAD

**Issue by marpaia** [facebook/osquery#1215]
Here's where we build/install Yara 3.3.0: https://github.com/facebook/osquery/blob/master/tools/provision/lib.sh#L157-L170

Here's the release for Yara 3.4.0: https://github.com/plusvic/yara/releases/tag/v3.4.0

**Comment by wxsBSD** [comment]
This should be a drop in replacement. I closely track the changes in YARA and am not aware of anything that would cause breakage in our usage. Only thing people will have to be aware of is that rules compiled with 3.4.0 should not work with older releases due to bytecode changes introduced in 3.4.0. So if you pre-compile your rules with 3.4.0 and load them on boxes running less than 3.4.0 you will have a bad time.

**Comment by marpaia** [comment]
https://github.com/Homebrew/homebrew/pull/40944
