### ISSUE TITLE
Commits to master should build an additional target that sets RELEASE=true

### ISSUE THREAD

**Issue by theopolis** [facebook/osquery#1304]
A commit to master triggers the following:
- make deps
- make test
- make packages

We can change it to:
- make deps
- make test
- make clean
- make release
- make test
- make packages

This will significantly increase the build times for merges into master and the resultant package creation. However, it will allow us to add unit tests and require a non-release build. These tests may include additional features that are removed for releases, a good example is the kernel tests. The kernel API for debug builds includes throughput and performance tests as well as API unit tests. For release builds these API calls are removed. 

By building "twice" we guarantee the most number of tests run 'per merge', and deployable packages on every build.

**Comment by mofarrell** [comment]
It seems like `make packages` already builds a release version.
Something like the following may work:

* make deps
* make
* make test
* (make kernel-load)
* (make kernel-test)
* (make kernel-unload)
* make packages                 (no clean needed only builds files with changing macros of files)
* make test

If the kernel is going to be included in the packages then some logic will need to be added to that process.  Otherwise this would work to build test both user land logic and kernel land logic, however would not build the release kernel-module.

**Comment by mofarrell** [comment]
#1311 will change the build process to the one I described.  Make packages builds a release version without performing a clean build already.
