### ISSUE TITLE
Installed osquery via Homebrew, packs are not in /usr/share/osquery

### ISSUE THREAD

**Issue by runasand** [facebook/osquery#1402]
When installing osquery on OS X via Homebrew, the packs are written to */usr/local/Cellar/osquery/1.5.0_1/share/osquery/packs/*. The osquery configuration file defaults to */usr/share/osquery* as the location for the packs. I'm not sure if you want to ship a different config just for OS X, so perhaps it would be good to just add a comment within the config file and the online documentation to point this out.

**Comment by theopolis** [comment]
Right! Does the homebrew install at least symlink our relative `./share/osquery/packs` to `/usr/local/share/osquery/packs`? :smirk_cat:

**Comment by runasand** [comment]
I see no symlinks and had to edit the paths in the config file manually for osqueryctl to be happy.

**Comment by theopolis** [comment]
Dang, we should be able to solve that with logic in the osquery formula.

If we can provide reliable links to `/usr/local`, modify the `osqueryctl` search logic (optional), and add a note to RTD about where to expect paths when installing through Homebrew-- we should be ok!

**Comment by runasand** [comment]
Turns out this is also an issue when installing the OS X package. The packs are in */var/osquery/packs/*, while the config file expects them to be in *//usr/share/osquery*.

**Comment by marpaia** [comment]
@runasand for what it's worth, the included configs are only meant to serve as a template really, not a definitive working copy on all platforms

**Comment by PickmanSec** [comment]
Yo, So when installing osquery I believe the packs should be included and be available. Whether they should be enabled by default should be left up to whether or not you believe that the vast majority of users run darwin (since the packs target Darwin mostly) but if you want the safe answer just leave them commented out. The other thing is when these queries run is there a way to differentiate between packs and the query ran in that pack in the logs? i.e. query name and pack name. This would help differentiate these logs for easier parsing.

**Comment by marpaia** [comment]
To be explicit, the packs are available, the issue here is that the default configuration file doesn't contain the correct file paths for the included packs, correct?

**Comment by runasand** [comment]
Correct. The default configuration doesn't contain the correct file paths for the included packs.

**Comment by DomT4** [comment]
At least for Homebrew, presuming the configuration files are generated & installed during compile, we can just `inreplace` the incorrect paths for correct ones at the end of installation.

**Comment by marpaia** [comment]
Part of me feels like the included configs are just examples. They're not necessarily meant to be useful for every use-case out of the box. osquery can be installed in a variety of different ways. If we go with the solution that @DomT4 mentions for Homebrew, should we also maintain that functionality for every other way that osquery can be installed on various operating systems?

I guess this more comes down to a question of how much of an example we want the example config to be. It's literally named `/usr/local/share/osquery/osquery.example.conf` on Homebrew installations. It was never intended use was never to be The Actual Config That You Use.

## My questions

- Is the general opinion that the example config should be useful/usable from the start? Or should it just serve as a comprehensive/customizable reference of available configuration options?

- Why do you want that config to work? Are you deploying osqueryd in your enterprise? If so, why are you using Homebrew instead of packages? Does your OS X configuration management support Homebrew? Or are you just testing it out?

- If you're just testing it out, why are you testing it out? Are you trying to get familiar with the tools so that you can deploy it at work? Or are you trying to maintain individual security by running osqueryd on your own host?

- If you're running osqueryd on your own host to improve your personal security posture, don't you also have to edit/create a LaunchDaemon so schedule osqueryd with the appropriate options and paths? If you're OK with configuring a LaunchDaemon, why aren't you OK with manipulating the actual osqueryd config?

**Comment by marpaia** [comment]
If the underlying motivation here is that there is an appetite for a personal version of osquery, I think that this issue is just one part of a whole series of tooling and infrastructure that would have to be created to make that a more friendly experience. If that's the case, then I'd be happy to talk through what an ideal "personal" osquery would look like. We have spent some time discussing this, but it has obviously never been brought to the finish line.

**Comment by theopolis** [comment]
How does everyone feel about #1463? It tries to capture the most helpful NUX but not enabling any packs by default and referencing the included pack locations for each platform and install method. 

Thanks for all the help and patience here!

**Comment by runasand** [comment]
@marpaia I would say that there is an appetite for a personal version of osquery and would be happy to discuss what an ideal "personal" osquery would look like. I realize most deployments so far are enterprise style, but I know of at least one home env user... :)

**Comment by marpaia** [comment]
@theopolis was 1463 a typo? it doesn't exist

**Comment by marpaia** [comment]
Ah, found it, it's #1436

**Comment by marpaia** [comment]
@runasand, awesome, if you get a chance to think it over, I'd love to hear your thoughts via an issue or something
