### ISSUE TITLE
safari_extensions table should include bundleID and developerID as criteria

### ISSUE THREAD

**Issue by arubdesu** [facebook/osquery#1418]
If Apple's xprotect (`/System/Library/CoreServices/CoreTypes.bundle/Contents/Resources/XProtect.meta.plist` as if y'all weren't aware) is any indication, it would be helpful to report malicious extensions with these two extra pieces of information. I'm currently grabbing it ([poorly, via JAMF](https://gist.github.com/arubdesu/152e6a29b8c9efa583a4)) via the following snippet (trimmed for relevant parts):
```
import glob
import sys
sys.path.append("/usr/local/munki/munkilib")
import FoundationPlist


CAUGHT_EXTENSION_LIST = []

SAFARI_WHITELIST = ['many.safariextz',
                    'different.safariextz',
                    'ones.safariextz',]

ALL_USER_SAFARIEXT_PLISTS = glob.glob('/Users/*/Library/Safari/Extensions/Extensions.plist')
for plist in ALL_USER_SAFARIEXT_PLISTS:
    list_of_dicts = FoundationPlist.readPlist(plist)
    for ext_info_dict in list_of_dicts['Installed Extensions']:
        if ext_info_dict['Archive File Name'] not in SAFARI_WHITELIST:
            caught_tuple = (ext_info_dict.get('Archive File Name'),
                            ext_info_dict.get('Bundle Identifier'),
                            ext_info_dict.get('Developer Identifier'))
            CAUGHT_EXTENSION_LIST.append("\n" + str(caught_tuple))
# print, return, etc.
```

**Comment by arubdesu** [comment]
Ha, although in this most recent case(some malarkey called Eliaho with 3 super sketchy-looking LaunchA's in the users home folder), of course those values aren't present...😅

**Comment by theopolis** [comment]
Wow, [`safari_extensions`](https://github.com/facebook/osquery/blob/master/specs/darwin/safari_extensions.table) needs some love. There's very little actionable information in that table. We might be able to add the XProtect blacklists into the existing `xprotect_entires` or create a new `xprotect_plugins` or `xprotect_blacklist` table that had more focused attributes like `identifier`, `version`, `developer_id`, `outdated` to boot.

**Comment by theopolis** [comment]
To get the `identifier` and `developer_id` into `safari_extensions` we will need to parse XAR files, these are the **safariextz** compressed bundles.

It looks like libxar is only maintained by Apple (since 2012). Apple/OS X provide the dynamic library and a `/usr/local/xar.h` by default. Writing some basic support for XAR is doable, but will most likely only be applicable for extensions.

Apple/OS X also provides a `libarchive.dylib` BUT does NOT provide a `archive.h`. This means we'd need to install the development headers from brew or vendor in the header from Apple's opensource repos. Version binding this would be difficult, whereas version binding the direct XAR support would be simple. I'm going to take a look across all of our supported platform and see if (1) libarchive's shared library is installed by default, and (2) if the ABI of the library is relatively similar.

**Comment by theopolis** [comment]
@arubdesu, with the latest from #1477, we should have those XProtect meta lists in `xprotect_meta` (thanks for pointing out we had missed those) and some more information into the `safari_extensions`:

```python
schema([
    Column("name", TEXT, "Extension display name"),
    Column("identifier", TEXT, "Extension identifier"),
    Column("version", TEXT, "Extension long version"),
    Column("sdk", TEXT, "Bundle SDK used to compile extension"),
    Column("update_url", TEXT, "Extension-supplied update URI"),
    Column("author", TEXT, "Optional extension author"),
    Column("description", TEXT, "Optional extension description text"),
    Column("path", TEXT, "Path to extension XAR bundle"),
])
```

I'm not yet sure what the `developer_id` data in XProtect refers too. But that's next on my list!
