### ISSUE TITLE
rpm_packages is slow

### ISSUE THREAD

**Issue by marpaia** [facebook/osquery#1439]
Got some feedback that rpm_packages is super slow. Let's gather more data and triage.

**Comment by marpaia** [comment]
CC @jacknagz

**Comment by jacknagz** [comment]
:+1:

**Comment by theopolis** [comment]
@jacknagz, do you mind sharing the query? Or was it a `select * from rpm_packages`, and are you seeing poor performance on all hosts-- as in the average CPU time for the query is very high?

**Comment by jacknagz** [comment]
`SELECT * FROM rpm_packages;` is the query, the performance (per osquery_schedule) across the fleet looks like this:

`search columns.executions!="0" | eval avg_cpu = (('columns.user_time'+'columns.system_time')/'columns.executions')`

columns.name | avg_cpu
------------ | -------------
rpm_packages | 131.246394
listening_ports | 21.606829
processes | 12.147000
setuid | 3.447314
installed_users | 0.894082
osquery_logsize | 0.523741
logins | 0.486064

**Comment by theopolis** [comment]
The culprit is iterating through the RPM database (a set of Berkeley DB files) using `rpmdbNextIterator`. I can't find a way to improve a complete scan using this librpm iterator.

A potential overkill experiment could be reimplementing the scanning using raw *bsddb* calls. There'd be a bit of configuration discovery, aka where the database files live, and documentation reading for how to retrieve information from the database set. Then at the end, there's no guarantee this will improve performance for a complete scan.

Unfortunately, unless someone wants to jump on this for fun later, this is a wontfix. :(
