### ISSUE TITLE
Include hashes of packages on osquery.io

### ISSUE THREAD

**Issue by marpaia** [facebook/osquery#1481]
This came in as a request in IRC.

**Comment by jacknagz** [comment]
sha256's for chef users :+1:

**Comment by theopolis** [comment]
sha256 hashes for each package will land shortly, the hashes will be included right below each of the stable package links! Unstable packages will not include hashes just yet since they are updated very frequently, it would mean the same number of automated commits to the website's repo, maybe one day.
