### ISSUE TITLE
Won't start on Ubuntu 14.04

### ISSUE THREAD

**Issue by finid** [facebook/osquery#1544]
Just installed osquery on Ubuntu 14.04, bit it won't start on boot. And when I do start it manually, I get this line in the log:

```
W1008 08:50:31.673343  1133 init.cpp:446] Error reading config: Error parsing the config JSON. Check the syntax.
```

Why won't it start on boot, even when the config file is in place, and what's that line in the log?

TIA

**Comment by pathcl** [comment]
@finid you need to create a config. Try to follow documentation available http://osquery.readthedocs.org/en/latest/installation/install-linux/

**Comment by 0xdabbad00** [comment]
@finid, try `cat /var/osquery/osquery.conf | jq '.'`to debug syntax issues with your json (likely will need to install `jq`)

**Comment by finid** [comment]
Thanks, @0xdabbad00, there's definitely something wrong with the config file.

```
parse error: Invalid numeric literal at line 2, column 5
```

**Comment by finid** [comment]
The file is heavily-commented, which appears to be a no-no, because all lines that `jq` is complaining about are comments lines.

**Comment by finid** [comment]
After stripping all the comments from the config file, it now starts without an error, but still won't start on boot.

After looking through the init script, it seems that a `osquery.flags` is required to be in place just like the config file. Is that correct?

TIA

**Comment by marpaia** [comment]
Hey, yeah, the parser that boost uses to parse JSON actually supports C and C++ style comments (lol, right?). Because of that, we started actually using them in example configs: https://github.com/facebook/osquery/blob/master/tools/deployment/osquery.example.conf

The obvious downside of this is that no other JSON parser supports comments, so it makes linting a commented config really hard. I don't suggest actually using comments in your config, it just complicates things. If you remove the comments / non-standard things, like it sounds like you have, then you should be able to get going no problem with a config as simple as:

```json
{
  "schedule": {
    "test": {
      "query": "select * from time",
      "interval": 1
    }
  }
}
```

Write that to `./example.conf` and, even if another osqueryd is running on your system, you'll be able to run that with: `osqueryd --config_path ./example.conf --db_path ./db --pidfile ./pidfile --logger_path ./logs --verbose --debug`

You should see output like:

```
$ osqueryd --config_path ./example.conf --db_path ./db --pidfile ./pidfile --logger_path ./logs --verbose --debug
I1008 21:26:51.651947 2064998400 init.cpp:263] osquery initialized [version=1.5.2-73-g709479b]
I1008 21:26:51.664877 2064998400 system.cpp:207] Writing osqueryd pid (65028) to ./pidfile
I1008 21:26:51.665982 528384 watcher.cpp:366] osqueryd watcher (65028) executing worker (65029)
I1008 21:26:51.673095 2064998400 init.cpp:260] osquery worker initialized [watcher=65029]
I1008 21:26:51.673874 2064998400 db_handle.cpp:124] Opening RocksDB handle: ./db
I1008 21:26:52.013805 1064960 events.cpp:507] Starting event publisher run loop: diskarbitration
I1008 21:26:52.013816 2064998400 daemon.cpp:39] Not starting the distributed query service: Distributed query service not enabled.
I1008 21:26:52.013814 1601536 events.cpp:507] Starting event publisher run loop: fsevents
I1008 21:26:52.013829 2138112 events.cpp:507] Starting event publisher run loop: iokit_hid
I1008 21:26:52.013849 2674688 events.cpp:507] Starting event publisher run loop: scnetwork
I1008 21:26:52.013934 3211264 scheduler.cpp:56] Executing query: select * from time
I1008 21:26:52.025944 3211264 scheduler.cpp:101] Found results for query (test) for host: hostname.local
I1008 21:26:53.056267 3211264 scheduler.cpp:56] Executing query: select * from time
I1008 21:26:53.056843 3211264 scheduler.cpp:101] Found results for query (test) for host: hostname.local
```

And you should just see those last two lines repeat every second:

```
I1008 21:26:53.056267 3211264 scheduler.cpp:56] Executing query: select * from time
I1008 21:26:53.056843 3211264 scheduler.cpp:101] Found results for query (test) for host: hostname.local
```

**Comment by finid** [comment]
Thanks, @marpaia, but after all that, how do I make it start at boot time?

**Comment by marpaia** [comment]
Use something like Chef, Puppet, etc. to maintain the lifecycle of the daemon via the init script: http://osquery.readthedocs.org/en/stable/deployment/configuration/#chef-os-x

**Comment by marpaia** [comment]
Keeping the daemon running is not an osquery issue, but more of a general linux question, so I'm going to close this out. Feel free to asked pointed follow-up questions if they arise.

**Comment by tprzel** [comment]
"worker_threads": "2",

I had to remove the comma from the above line.
