### ISSUE TITLE
Query failing causes other queries to fail.

### ISSUE THREAD

**Issue by PickmanSec** [facebook/osquery#1556]
I have a ospacks running and not all of the queries seem to be running. I looked in the logs and noticed that one of the workers appears to be failing.

W1012 11:11:11.111111 181559296 watcher.cpp:296] osqueryd worker (61641) system performance limits exceeded

This seems to be connected with the other queries not running.

**Comment by marpaia** [comment]
If the performance limits are exceeded, the worker is killed and a new worker is spawned, which restarts the schedule. Thus, if you have a query scheduled to run every 10 seconds and a query scheduled to run every 20 seconds, but the query which runs every 10 seconds always causes the worker to quit, the next query will never get executed because the schedule never makes it far enough. Try relaxing your performance limitation options and/or removing offending queries.

**Comment by PickmanSec** [comment]
The queries are not scheduled to run every 10 secs but these queries are to the spec at which you default to when osquery is installed(these are the default ospack queries). So a user who just installed osquery wouldn't be able to use osquery to do even the default features?

**Comment by theopolis** [comment]
Hey @PickmanSec! If you're using version 1.5.3 you should also get some WARNING lines about the query that failed.

The performance limits are enforced by a watchdog thread that checks the rolling average of CPU time spent executing queries. If the `osqueryd` process takes up too many relative cycles, say 60% CPU for 3 seconds then the process is restarted and that query is skipped. It's possible that some queries are missing because of this! Since the schedule is splayed at runtime, a restarting process will receive difference splayed values. A query will be skipped if a splay is recalculated to an interval modulus of before the failing query.

This is definitely a problem!

**Comment by PickmanSec** [comment]
Thanks for picking this up.

**Comment by PickmanSec** [comment]
So on that issue it seems like the issue might be even deeper then that. Since if what you are saying is the issue we should still see queries run after the initial failure but, we do not see any queries run after the problem query fails.

**Comment by theopolis** [comment]
A few things need to be done for this:
- [ ] the performance limit default should be set to 0, meaning loose limits but acceptable.
- [ ] the calculated splays should be rather consistent between restarts. See [1]
- [ ] the `osquery_info` and `osquery_schedule` should be decorated with more info about start/last execute.
- [ ] a last-executed query should be emitted to INFO on restart if there is no dirty bit (otherwise a WARNING log is emitted). See [2]

1. A splayed query in the schedule can store its splay until the interval changes or perhaps the config is updated.
2. The time in seconds when a query was last executed should be added as a column to `osquery_schedule`, one can always deduce the last time a query has been executed. These values should persist in RocksDB; it may be weird on the next `osquery_schedule` query after a restart since `executions` will be 0, but `last_executed` will be non-0. Let's think this through.

Overall, we should see more reliability/determinism from the schedule.

**Comment by PickmanSec** [comment]
This sounds like a good start, I will think over these things and hopefully have some input on the value of these things.

**Comment by theopolis** [comment]
Ok, I'm ready to roll with calling this solved. The only thing not included with #1621 that would be helpful is blacklisting the failing query(s) for a period of time. Right now they emit a log and will be executed again when their schedule interval dictates.

**Comment by theopolis** [comment]
The main issue/bug here is the [reseed of schedule time](https://github.com/facebook/osquery/pull/1621/files#diff-888b4707cbdedc29bc1bdabf69949d1eL117). It was being `% 60` meaning a failing query that caused the worker process to stop would blind the rest of the schedule.
