### ISSUE TITLE
Not everybody have installed sudo

### ISSUE THREAD

**Issue by pathcl** [facebook/osquery#1567]
Ok, this works for debian GNU/Linux stretch/sid (amd64). Bare netinstall installation.

root@somevm:/home/pathcl/src/osquery# make
cd build/sid && cmake ../../ && \
	CTEST_OUTPUT_ON_FAILURE=1 make --no-print-directory
-- Cannot find git submodule third-party/sqlite3 directory
-- Please run: make deps or git submodule update --init
CMake Error at CMakeLists.txt:188 (message):
  No sqlite3 directory

-- Configuring incomplete, errors occurred!
See also "/home/pathcl/src/osquery/build/sid/CMakeFiles/CMakeOutput.log".
Makefile:26: recipe for target 'all' failed
make: *** [all] Error 1
root@somevm:/home/pathcl/src/osquery# make deps
./tools/provision.sh build build/sid
[+] detected debian (sid)
/home/pathcl/src/osquery/tools/provision/debian.sh: line 45: sudo: command not found
Makefile:82: recipe for target 'deps' failed
make: *** [deps] Error 127

Easy to fix:

/home/pathcl/src/osquery/tools/provision/debian.sh

 44 function main_debian() {
 45 if [[ ! -f /usr/bin/sudo ]]; then
 46     echo "Please install sudo in this machine"
 47     exit 0
 48 fi

**Comment by theopolis** [comment]
Hi @pathcl! Would you mind sending a PR to add this check (maybe here: https://github.com/facebook/osquery/blob/master/tools/provision.sh#L27) or add a note in the wiki that lists sudo as a requirement: https://github.com/facebook/osquery/blob/master/docs/wiki/development/building.md?

**Comment by pathcl** [comment]
Hello @theopolis I've just submitted a PR and also added to building.md

**Comment by theopolis** [comment]
I see the two branches you opened on your osquery fork:

patch-1: https://github.com/pathcl/osquery/commit/3e86e64757dc0ca2233a4c396a7f2ee4bad63477
patch-2: https://github.com/pathcl/osquery/commit/f1621340bfc6b1a5ecbb8e15a194250d3621f2b5

These do not automatically become pull requests, please read some of the Github docs on PRs: https://help.github.com/articles/creating-a-pull-request/

Ideally, since this is a single issue, and since both patches are related, you'll want a single PR. If you would rather checkout the repository, make the edits on your local master, create a single commit, and post the git email diff, or commit back to your fork's master, we can open a single PR with edits to both files.

**Comment by pathcl** [comment]
@theopolis my bad! I've fixed in only one PR. Thank you.
