### ISSUE TITLE
search function on document site (https://osquery.readthedocs.org/en/stable/) is inconsistent or broken

### ISSUE THREAD

**Issue by zenfish** [facebook/osquery#1569]
Not sure if the dox site gets issues reported here or not, but....

Tried searching for "certificate" from "https://osquery.readthedocs.org/en/stable/" and get:

    Results for certificate
    No results found. Bummer.

Try the same search from google ("certificate site:https://osquery.readthedocs.org/en/stable/") and it comes up with two hits, both under en/stable:

    https://osquery.readthedocs.org/en/stable/deployment/remote/
    https://osquery.readthedocs.org/en/stable/development/kernel/

Grepping from the command line reveals a third hit:

    $ grep -irl certificate docs/
    docs//wiki/deployment/remote.md
    docs//wiki/development/kernel.md 
    docs//wiki/installation/cli-flags.md

When I tried to find the 3rd one above, cli-flags, I just typed in flags from https://osquery.readthedocs.org/en/stable/, and got one hit:

    osquery - third-party/rocksdb/INSTALL/index
    ... flags processing. You can compile rocksdb library even if you don't have gflags installed...

But when I clicked on the link in the result, it goes to a "This page does not exist yet" result:

    https://readthedocs.org/en/stable/third-party/rocksdb/INSTALL/?highlight=flags

Also, not able to reproduce right now, but I've landed on pages like:

    https://osquery.readthedocs.org/en/installation/cli-flags.md

And the result + links are all broken, like:

    Requested version seems not to have been built yet. But these versions are available.
    [....]

(e.g. https://osquery.readthedocs.org/en/installation/cli-flags.md)

The only thing worse than not having a search function is one that lies to you :)

**Comment by theopolis** [comment]
This isn't within our control. :cry:

The documentation is published to [ReadTheDocs](https://readthedocs.org/), all the searching happens within their tool. Here is a link to their project: https://github.com/rtfd/readthedocs.org. I haven't researched the source of the breakage, but your analysis seems pretty good, maybe search/open/reference an issue there?

**Comment by zenfish** [comment]
If you don't want to fix problems in your official documentation site... I wonder what the point of having it is. You chose the technology to use; your concern for your user base is touching.

I won't bother filing more issues here, such as the lack of guidance or documentation on certificates (including no guidance on self signed certificates), but the responses so far are clear - we'll document what we want, it's good enough, and if don't like it go jump in a (virtual?) lake. I was walking through code trying to get deployments working, but really, what's the point.  I've done enough greps and finds on your code to know the project far prefers code over dox, like most engineers.

Best of luck.

**Comment by theopolis** [comment]
> your concern for your user base is touching.

I hope you don't mean this? :cry: We put a LOT of time into helping everyone we can, this ranges from having a documentation site, to helping new C++ developers get some code into our repository, and working day and night providing help in IRC, on Slacks, Github issues, Google Groups, doing VCs for IR teams, including this in our bug bounty program, giving workshops and tutorials at conferences, and more.

> but the responses so far are clear - we'll document what we want, it's good enough, and if don't like it go jump in a (virtual?) lake

That's again, pretty harsh, I feel that has NOT been your experience at all. I have put a non-trivial amount of [time](https://github.com/facebook/osquery/pull/1551) into refactoring our documentation, engaging with other integration projects, and making additions you asked for in your other [issue](#1540); AND that documentation issue is a blocker for our next release.

Generally the type of comment you left above is not helpful. You have identified a problem, failed to provide a solution, made some personal attacks against how we treat our community, in which we are definitely a part of too! Please please please, know that we try everything possible to be helpful. If you find something that truly upsets you, at least reason that the origin of the problem was not wrought from wanting to disrespect our community. Why would we think like that? But at the very least provide a solution along side your critical feedback!

Here's where my head is at: (1) I've set up the RTD site after identifying a duplication of information and non-maintenance/discovery problem with Github's wikis. YES, we used to have tons of content in our Github wiki and it was difficult to migrate to RTD, but despite the search problem with RTD the user-guide/walk-through flow has made it much easier for folks. We get positive feedback about RTD all the time! (2) I don't know of any other solution! TONS of projects use RTD and the problem you have identified is systemic throughout all of them. I have pointed you to their code base, search through their issues and you'll find a few calling out the search problems. I do not think our choice of RTD is in any way us attempting to disrespect our community nor does it reflect in any way on the project's selfishness or laziness.

**Comment by marpaia** [comment]
I don't think this issue is constructive, so I'm going to close it. If search is super key and the google `site:` isn't working out, we would need to move to another wiki provider or file an issue on read the docs itself. If those are options that we want to move forward with, we can file an issue on those.
