### ISSUE TITLE
Registering sql queries for update/change events through SDK 

### ISSUE THREAD

**Issue by sami2316** [facebook/osquery#1620]
Question:
As per my understanding, OSquery SDK provides ```query()``` and ```queryExternal()``` functions to get current table of given SQL query. I am interested in changes of query table (update); one way is to use ```queryExternal()``` at two different times and then using ```diff()``` get the changes(added or removed). But this method is not efficient, in a sense -- what if some event is added and removed between the two queries interval. 
I am wondering; is there way to register for events? So that we may get updates for each subscribed query without using ```diff()```  technique. I believe ```osqueryd``` must be using events approach but I could not figure out the event approach through SDK.

**Comment by theopolis** [comment]
Sort of, there are a few tables that only include streams of events rather than state of the system. An example is [`hardware_events`](https://github.com/facebook/osquery/blob/master/osquery/tables/events/darwin/hardware_events.cpp), the table implementation does not look familiar because it is not returning a `QueryData` but rather saving a single row at a time that represents an event. From SQL and the shell/daemon's perspective you can still `select * from hardware_events` because "at query time" the table is just fetching the saved event rows and returning them.

For "normal" tables, usually those that do not include `_events` in the name, they are representing the current state of some OS concept. The only way to turn that concept into an event stream is do exactly what you mentioned and perform a differential between two points in time. An effective stream would balance frequency of polling/diff against the performance impact a select has on the system.

Where ever possible I encourage folks to write `_events` type tables, but those require some existing OS API that allows user space applications to request notification/callbacks when the specific events occur. Here's a bit more about these tables: http://osquery.readthedocs.org/en/stable/development/pubsub-framework/

**Comment by sami2316** [comment]
Can we access ```files_events``` table through ```osqueryi```? I have tried at two centos machines but ```SELECT * FROM file_events``` returns nothing. Although, my general understanding and observation is; we can excess ```_events``` tables through ```osqueryi``` interface.

**Comment by theopolis** [comment]
Hey @sami2316, you can access `file_events` through `osqueryi` as long as the events happened while the `osqueryi` process was running, and thus the INotify/FSEvent event publishers were running and writing to your RocksDB instance.

In most cases the `osqueryi` process does not live long enough to "see" these events so you use an `osqueryd` that **usually** writes events to a separated, dedicated RocksDB. This by default is `/var/osquery/osquery.db`. Which is owned/restricted to write/read by the super user. If you want to "browse" events using the shell you can:

```
$ sudo osqueryi --database_path /var/osquery/osquery.db
```

Be very careful when doing this for 2 reasons:

1. The first process that accesses a RocksDB instance requests a RW lock. If an `osqueryi` has this RW lock on the daemon's RocksDB and the daemon attempts to start-- the daemon will fail. This is because the shell CAN open an instance RO, but the daemon has logic that forces is to require RW.

2. There are options and flags that control event flushing. The default life/age of an event is a day. If you select from the `_events` table you may expire these cached events. This can be disabled with  `--events_optimize=false` or `--events_expiry=0`. I say be careful here because by opening a RW RocksDB and selecting from those tables will remove the events. If you have a scheduled query that also selects those tables, it may miss the events.

**Comment by theopolis** [comment]
Hey @sami2316, I think this will work, based on our discussion here and within the "#bro" channel on the osquery Slack: https://github.com/facebook/osquery/pull/2088

**Comment by theopolis** [comment]
I haven't heard any complaints/issues/requests here. Feel free to re-open if we need to continue to work on the `::logEvent` API.

**Comment by sami2316** [comment]
@theopolis I could not get your message here and I was expecting it at slack. I am going to work on it now. And for sure, I will approach you in case of any issue.

**Comment by sami2316** [comment]
@theopolis I have tried updating to latest version and trying to compile example extension with external build system as initial step (After that I would be able to test logger plugin). But I am getting following linkage error. Can you spot the error? 
```
Linking CXX executable example_extension.ext
CMakeFiles/example_extension.ext.dir/src/ExampleExtension.cpp.o: In function `main':
ExampleExtension.cpp:(.text+0xa53): undefined reference to `osquery::Initializer::requestShutdown(int)'
ExampleExtension.cpp:(.text+0xa58): undefined reference to `osquery::Initializer::waitForShutdown()'
CMakeFiles/example_extension.ext.dir/src/ExampleExtension.cpp.o: In function `osquery::ExternalSQLPlugin::getQueryColumns(std::string const&, std::vector<std::tuple<std::string, osquery::ColumnType, osquery::ColumnOptions>, std::allocator<std::tuple<std::string, osquery::ColumnType, osquery::ColumnOptions> > >&) const':
ExampleExtension.cpp:(.text._ZNK7osquery17ExternalSQLPlugin15getQueryColumnsERKSsRSt6vectorISt5tupleIISsNS_10ColumnTypeENS_13ColumnOptionsEEESaIS7_EE[_ZNK7osquery17ExternalSQLPlugin15getQueryColumnsERKSsRSt6vectorISt5tupleIISsNS_10ColumnTypeENS_13ColumnOptionsEEESaIS7_EE]+0x2b): undefined reference to `osquery::getQueryColumnsExternal(std::string const&, std::vector<std::tuple<std::string, osquery::ColumnType, osquery::ColumnOptions>, std::allocator<std::tuple<std::string, osquery::ColumnType, osquery::ColumnOptions> > >&)'
collect2: error: ld returned 1 exit status
make[3]: *** [example_extension.ext] Error 1
make[3]: Leaving directory `/home/chenone2316/OFFICE_WORK/Development/Extension_testing/build'
make[2]: *** [CMakeFiles/example_extension.ext.dir/all] Error 2
make[2]: Leaving directory `/home/chenone2316/OFFICE_WORK/Development/Extension_testing/build'
make[1]: *** [all] Error 2
make[1]: Leaving directory `/home/chenone2316/OFFICE_WORK/Development/Extension_testing/build'
make: *** [all] Error 2
```

**Comment by theopolis** [comment]
Make sure you've built and are linking the latest code from master, that `osquery::Initializer::requestShutdown(int)` symbol does exist. I promise: https://github.com/facebook/osquery/blob/master/osquery/core/init.cpp#L594

**Comment by sami2316** [comment]
@theopolis I had build against the latest code from master but i was messing up something. Now, I have build on a new machine and ```osquery::Initializer::requestShutdown(int)``` symbols issues are resolved. But there exist the following error:
```
Linking CXX executable example_extension.ext
CMakeFiles/example_extension.ext.dir/src/BrokerQueryPlugin.cpp.o: In function `osquery::ExternalSQLPlugin::getQueryColumns(std::string const&, std::vector<std::pair<std::string, osquery::ColumnType>, std::allocator<std::pair<std::string, osquery::ColumnType> > >&) const':
BrokerQueryPlugin.cpp:(.text._ZNK7osquery17ExternalSQLPlugin15getQueryColumnsERKSsRSt6vectorISt4pairISsNS_10ColumnTypeEESaIS6_EE[_ZNK7osquery17ExternalSQLPlugin15getQueryColumnsERKSsRSt6vectorISt4pairISsNS_10ColumnTypeEESaIS6_EE]+0x2b): undefined reference to `osquery::getQueryColumnsExternal(std::string const&, std::vector<std::pair<std::string, osquery::ColumnType>, std::allocator<std::pair<std::string, osquery::ColumnType> > >&)'
collect2: error: ld returned 1 exit status
make[3]: *** [example_extension.ext] Error 1
```
What's the possible reason?

**Comment by sami2316** [comment]
@theopolis I have played with the logEvent() function. When I generate event within sample code with `` osquery::Registry::call()`` logEvent captures events. But when I run ``osqueryd `` with process query in ``osquery.conf``` I don't get any event via logEvent(). Although the active logger plugin is my examplePlugin but still no events are forwarded to logger plugin. 
When I researched more, I came to know about event-subscriber plugins; do I need to register subscriber plugin for all events?
