### ISSUE TITLE
Writing to Two Loggers at Once

### ISSUE THREAD

**Issue by sroberts** [facebook/osquery#1648]
One of the things that would ease my deployment woes would simply be the ability to write to more than one logger at the same time. There are nice things you can do having logs sitting on the host, but I also want to take advantage of the TLS logger. I can certainly hack something up to do this, there are a few methods, but having this officially supported would be much cleaner. Thanks for considering!

**Comment by theopolis** [comment]
I love this concept! I would break it into feature requests:

- [ ] Support a comma-delimited **set** of logger plugins instead of just one. 
- [ ] Allow each query in the schedule or pack to specify an explicit logger, then results from that query are ONLY written to the logger defined.

That second ask is a little tricky as I would like to not enable a logger plugin globally, but have it enabled for a specific query. The use case here is for Linux and the auditd "support", which essentially turns off the actual auditd process. This totally violates the auditd/audisp architecture but is quite a bit faster and safer IMO for the deployments I'm testing/considering where I can explicitly control auditd via chef. BUT I would like several of the audit message types to go into syslog still. In this example the audit user-related table would have a query:
```json
"user_events": {
  "query": "select * from user_events;",
  "interval": 60,
  "removed": false,
  "logger": "syslog"
}
```

@sroberts, you're interested in the first request right, sending all result logs to multiple loggers?

**Comment by sroberts** [comment]
@theopolis I could certainly find uses for the second feature as well (having specific logs to go to a specific logger) so I'd call it a "nice to have", but my primary interest is the first one, having all queries write to multiple loggers (in particularly syslog & TLS). I've got some ideas for making logs available for the user (thus local syslog) while also being aggregated remotely (thus TLS).

**Comment by theopolis** [comment]
Ok cool, I agree, let me try real quick to see how hard this would be. FYI check out #1647, which will change the syslog output format.

**Comment by theopolis** [comment]
@sroberts, question: does it make sense to log status (ERROR/WARNING) and results to both loggers?

I am playing with two incantations of the API:

1. You can set `--logger_plugin=filesystem,syslog` and you get a teeing of all logs everywhere to both.
2. You can set `--logger_additional_plugin=syslog` and you can replicate results to a secondary/additional plugin.

The second form can be expanded to run setup on each of those plugins (essentially an initialize) such that you can specifically target them within queries as opposed to a blanket teeing of results. This is a bit more complicated (as described above) and will require a few more flags.

**Comment by sroberts** [comment]
@theopolis In my mind I saw the second logger as a perfect mirror. I think that errors and such can be handled by the consumer.

**Comment by sroberts** [comment]
@theopolis: ![](http://media1.giphy.com/media/j5IdWWOAYzcli/giphy.gif) :sparkles:

**Comment by sroberts** [comment]
@theopolis I'm looking to implement this (finally) and went looking for documentation into how to do this. Did that ever make it into readthedocs?

**Comment by theopolis** [comment]
It show's up here: https://github.com/facebook/osquery/blob/master/docs/wiki/installation/cli-flags.md#loggingresults-flags (but that's not reflected in the stable docs yet). It would be nice to add that to the logging deployment page too.

**Comment by sroberts** [comment]
Ahhh... good to know. Thanks.
