### ISSUE TITLE
Idea: add a primary key concept to tables

### ISSUE THREAD

**Issue by defunctzombie** [facebook/osquery#1654]
**Use case**

When receiving steaming events via the logging endpoint (using the TLS plugin) these events take the form of `added` or `removed` event types. These deltas can easily be used to keep a copy dataset updated with changes from a node; however, each particular table has its own set of columns so when a `removed` event is received, the way to find an existing item is not clear since not all of the columns are unique but some could be considered unique.

This would also allow the `removed` event type to be a smaller payload as only the primary key would need to be sent in such cases. Right now it seems that a remove event contains all of the values of an added event effectively making the entire record the "key" (see gotchas below).

**Solution(s)**

Add a notion of a primary key per table. This field name could be consistent across tables (id, _id, etc) that support such a notion (some tables might not be able to support it).

Add a notion of a primary key field to just the logging output for remove messages. This would be additional metadata next to the `node_key` like `primary_field_name` or similar.

**Gotchas**

One trick I currently use is to hash all of the field values to produce a key for the record, but I am unsure if a remove event always mirrors the values of an added event so having a specific primary key field or concept can solidify this.

Looking at the event steam, events for tables like `mounts` seems to send a remove/added pair for an existing mount when the mount blocks_available changes, etc. I believe this is because there is no `update` event and the remove values must be present to correctly find the row for a corresponding added event.

**Comment by theopolis** [comment]
I like this concept a lot, it will have several logical improvements when reasoning about the OS changes from the log stream perspective, as well as have performance improvements when determining changes post query execution.

Aside from determining the right set of changes to implement the primary key identification for removals and a nice way to represent updates, we need to consider that each scheduled query is essentially a view. When we schedule:

```sql
SELECT * from osquery_info join processes using (pid);
``` 

It's clear there is a primary key `pid` but the columns associated with this scheduled query are potential amalgamations of several primary keys from the `osquery_info` and `processes` table.

#### Approach Proposal: Preserving schema

The tables are implemented as a `TablePlugin` class with members that include the table name and column schema as a `std::map<std::string, ColumnType>`. We can add another member that identifies a key in that map representing the primary key. Better yet it can return a vector of keys if the primary key happens to be several columns. This is consistent with the assumption that scheduled queries may contain selected primary keys from multiple tables.

```cpp
class osqueryInfoTablePlugin : public TablePlugin {
 private:
  TableColumns columns() const {
    return {
      {"pid", INTEGER_TYPE}, 
      {"version", TEXT_TYPE}, 
      {"config_hash", TEXT_TYPE}, 
      {"config_valid", INTEGER_TYPE}, 
      {"extensions", TEXT_TYPE}, 
      {"build_platform", TEXT_TYPE}, 
      {"build_distro", TEXT_TYPE}, 
      {"start_time", INTEGER_TYPE}
    };
  }
  QueryData generate(QueryContext& request) {
    auto results = tables::genOsqueryInfo(request);
    return results;
  }
};
```

Becomes:

```cpp
class osqueryInfoTablePlugin : public TablePlugin {
 private:
  TableColumns columns() const {
    return {
      {"pid", INTEGER_TYPE}, 
      {"version", TEXT_TYPE}, 
      {"config_hash", TEXT_TYPE}, 
      {"config_valid", INTEGER_TYPE}, 
      {"extensions", TEXT_TYPE}, 
      {"build_platform", TEXT_TYPE}, 
      {"build_distro", TEXT_TYPE}, 
      {"start_time", INTEGER_TYPE}
    };
  }
  std::vector<std::string> keys() const {
    return {"pid"};
  }
  QueryData generate(QueryContext& request) {
    auto results = tables::genOsqueryInfo(request);
    return results;
  }
};
```

It is not yet possible to deduce the columns a scheduled query will "act" on using the SQLite prepared statement APIs. I fleshed this request into part 5 of #1651. This may be solvable using the SQLite query planner and tracking each opened virtual table, the column index requested, and by tracking where that column ends up throughout applied expressions within the row's column order.

Observation: if I perform some aggregation or comparison on a primary key column within the query select the scheduled query "view" cannot use that column as a pkey, right? This means we need to track each expression applied to selected primary keys and potentially discount their use for update/removed.

After a scheduled query is executed the results are compared to the results from the last time that query was run. This is a `log(n*n)` differential comparison that I'd like to remove. If a table plugin implements a primary key then it reduce this to the search time of a key access in a `std::map`. 

The log format will be slightly modified for removed events as you mentioned. I propose that if a table implements a primary key then the "removed" line only include the columns associated with the key, in most cases this will be a single column.

#### New feature: "`update`" action

Right! There is no `update` concept, only `added` and `removed`.

Using the approach above we can add `update` as a change to columns associated with an existing primary key. In this case the primary key fields and others will all be included in the `columns` embedded dictionary. This will be a bit hard to identify what the primary key is for the table associated with the row. Since you only know the name of the query you cannot consult another lookup table for the key.

The possible solution to make that less difficult is to include a new key for "update" actions that includes another embedded dictionary of the columns/values representing the primary key for that updated row. That is a bit of information duplication.

Definitely interested/eager to hear your thoughts!

**Comment by defunctzombie** [comment]
What you described sounds perfect and would open up the possibility for `update` actions and simpler `remove` actions which helps lower data transfer after initial host data sync.

The only thing I would add along with primary keys is some way to ask osquery for that information or have that information be provided with query updates (in the stream). In trying to think about how one might implement an `update` or `remove` event stream handler the receiver would need to have knowledge of the primary key(s) of a table to effectively lookup by those keys. This would either need to be prior knowledge in the stream processor or the stream itself (possibly the document) would have a meta field listing the primary key(s). This way, the event consumer can be mostly agnostic about the required data field storage/lookup (if using a document data store) instead of relying on being updated when downstream primary key changes in the agent.

**Comment by theopolis** [comment]
We now have a `INDEX` and `REQUIRED` table "attribute", this is beyond the scope of SQL but allows us some flexibility in describing (1) how the table behaves, and (2) how columns and `WHERE` predicates affect the results. https://github.com/facebook/osquery/pull/2431/files

We're getting closer. :)
