### ISSUE TITLE
Chrome Browser history

### ISSUE THREAD

**Issue by PickmanSec** [facebook/osquery#1691]
I was wonder what the feeling was about adding a chrome history table? I would like to but there are clear privacy concerns here.

**Comment by headmin** [comment]
definitely big privacy concerns, could be a kill criteria i.e. such implementation to osquery will result in imminent problems to use the technology at many public/private customers with/without workers union in europe.

**Comment by PickmanSec** [comment]
Interesting, I had not considered its use outside the country. You have a good point, I wonder if protections of the information would work such as, encrypting the data with a public key that the legal department has control of.

**Comment by headmin** [comment]
I doubt that encryption will help much here in case you need to discuss this. we all know if you want to collect this info you could easily do so as an admin - this would be a "proactive action" most of the time, but osquery will gather data in an automated fashion and as such collecting metrics, certificates state of files etc. could be considered OK (aka would survive discussions) but you'll cross a very fine line the moment you'd uses same process as an "passive action" to auto collect such private data (file contents, email conversations, messages and browser history).

**Comment by PickmanSec** [comment]
That make sense, I do agree with your reasoning. What if this was part of response action taken only if some other conditions were met?

**Comment by headmin** [comment]
Hm interesting, I wonder and love to learn how such conditions would be described in detail with osquery. If I stick to the example I'd say such an incident is partly why we've have introduced multiple Probes/Notification targets in Zentral - i.e. a specific osquery/Probe will notify higher ranks in security team, all further required actions to remediate the issue can be started as required on levels of human resource, administration force and forensics. Such process would meet criteria in public/private organisations we'd mostly deal with in Europe.

**Comment by theopolis** [comment]
This was brought up a **long** time ago (#22). It set the tone for what data osquery would focus on as there was resounding support for privacy over detection capabilities. In almost all cases, external threats could be detected and remediated without collecting browsing history from a client. 

More academically (and architecturally), it's possible to support surgical collection of private information from an enterprise-owned asset given a set of decisions from the machine users, machine owners, and machine defenders. This means a set of options that by default preserve privacy, but may be configured by a machine user and/or machine owner/defender. That configuration could enable things like browser history, etc as a potential table for the query schedule or limited to distributed/ad-hoc queries. This is still a potential deploy-blocker as something that doesn't enable a feature by default still has that feature.

More realistically, no one has provided a high enough priority reason or suitable architecture implementation to begin reasoning about legitimate pros/cons. Because of this we are sticking with the privacy preserving philosophy and not writing/merging tables like browser history. 

A shameless plug for [extensions](http://osquery.readthedocs.org/en/stable/development/osquery-sdk/): if this is something you **really** need you can definitely write a [module](https://github.com/facebook/osquery/blob/master/osquery/examples/example_module.cpp) or extension to add the table!

**Comment by headmin** [comment]
thanks Teddy for official words here. such discussion is important to follow, I'm happy to point to this issue as reference.

**Comment by theopolis** [comment]
@headmin, @PickmanSec I added this table to the master SQL roadmap under a new section called "anti-pattern" to add some posterity to the discussion here. Hopefully it doesn't sound too draconic from a "no we'll never do that perspective", but rather, more information/discussion welcomed, but here's our current thought/opinion-- then linked this task.

**Comment by PickmanSec** [comment]
Awesome, I am going to close this issue since my question was answered and position was reached.
