### ISSUE TITLE
pid connection state mac os x

### ISSUE THREAD

**Issue by pathcl** [facebook/osquery#1759]
Hello!

Is there a way to get a socket state on Mac OS X? as in linux: LISTEN, ESTABLISHED, FIN_WAIT, etc. I've looked into [0] and listening_ports table without finding any clue.

[0] https://osquery.io/docs/packs/#incident-response_open_sockets

**Comment by theopolis** [comment]
I don't think we expose the TCP state of the TCP connections in `listening_ports` is there a reason this is important to you? And is that need isolated to OS X?

`listening_ports` is a meta table generated by parsing the `process_open_sockets`. If we wanted to capture state of a TCP connection we'd need to expand that a bit. In Linux this is simple since that data is parsed from `/proc`, on OS X I imagine the state exists but it would be a bit of work to investigate and extend the tables.

**Comment by pathcl** [comment]
@theopolis not any specific reason I only was looking for something similar to 'netstat -putan' (on linux) available on osquery. However a friend came up with this: 

osqueryi "select pr.name AS protocol, pos.local_address || ':' || pos.local_port AS 'Local Address', pos.remote_address || ':' || pos.remote_port AS 'Foreign Address', p.pid || '/' || p.name AS 'PID/Program name' FROM process_open_sockets AS pos JOIN processes AS p ON p.pid = pos.pid JOIN etc_protocols pr ON pos.protocol = pr.number WHERE (pos.path <> '' OR pos.remote_address <> '') AND (pr.number = 6 OR pr.number = 17) AND pos.local_port > 0 ORDER BY pos.family ASC, pr.number ASC, pos.local_address ASC;"

It might be helpful for somebody.

**Comment by fmanco** [comment]
Closing as it looks solved.
