### ISSUE TITLE
Duplicate instance checks are abstracted per-platform

### ISSUE THREAD

**Issue by dguido** [facebook/osquery#1992]

**Comment by yying** [comment]
Currently, duplicate instance checks are disabled to deal with linker errors. The porting process will begin after we establish that we can generate an unit test executable.

**Comment by artemdinaburg** [comment]
Moved this task to the Service Functionality milestone. Originally we were going to implement duplicate instance checks via Mutex. However, these checks are only used in the daemon to see if an instance of osquery is already running. In Windows, osquery will be a windows service, and these checks will be done by asking the service manager. Therefore it makes a lot more sense to move this task with service milestone, since the service will be required to test it.
