### ISSUE TITLE
Tests for duplicate instance abstraction

### ISSUE THREAD

**Issue by dguido** [facebook/osquery#1993]

**Comment by yying** [comment]
Similar status of #1994

**Comment by artemdinaburg** [comment]
Moved this task to the Service Functionality milestone. Originally we were going to implement duplicate instance checks via Mutex. However, these checks are only used in the daemon to see if an instance of osquery is already running. In Windows, osquery will be a windows service, and these checks will be done by asking the service manager. Therefore it makes a lot more sense to move this task with service milestone, since the service will be required to test it.
