### ISSUE TITLE
Configuration Hardening Support

### ISSUE THREAD

**Issue by jarretraim** [facebook/osquery#2047]
I've been thinking of how to achieve configuration hardening and monitoring with osquery and wanted to get some advice before thinking about code. Basically, I'd like to be able to set out an expectation of what a setting on a host should be and then log / alert if the host doesn't meet that expectation. 

For example, the PermitRootLogin setting in /etc/ssh/sshd_config should be uncommented and set to no.

From a high level, it seems like there are two ways to go about this. 

(1) Create a new table that includes configuration settings. Something like:

| Column | Type | Description |
| --- | --- | --- |
| target_path | TEXT_TYPE | Path of the file the setting belongs to, e.g. /etc/ssh/sshd_config or HKEY/xxx/xxx/xxx |
| key | TEXT_TYPE | The name of the setting |
| value | TEXT_TYPE | The value of the setting |
| active | INTEGER_TYPE | Boolean for if the setting is present and enabled |

This approach would require a place to specify which files and registry keys should be monitored (though we'd probably just pull the entire registry in if possible). The code would also have to know how to parse various configuration files (a hard problem to cover in total, but an 80% solution isn't difficult). 

(2) Create a query that just dumps the contents of the specified file in to the log stream and allow the log receiver to do the heavy lifting. The easiest way to do this seems to be to extend the file_events table to include the contents of a file.

I'd like to get some thoughts about how to go about solving this problem, either by extending osquery with new capabilities or by building more logic into the logging platform.

**Comment by theopolis** [comment]
Hey @jarretraim, sorry it has taken me so long to reply!

I think the hybrid of (1) and (2) would be outstanding. Essentially we can provide some table APIs that allow for new configurations to be parsed into this schema easily. Then it is up to enterprising folks, as well as us, to opt-in several of the very valuable configuration files. When I say "opt-in" I mean do exactly as you explain, some heavy lifting / parsing.

Then you can provide a dedicated table for each and nix the `target_path` column.

The `target_path` is only helpful if there are potentially multiple configuration files yielding options. So for applications that support a "name.conf.d" folder, where therein are extensions to the configuration, THEN a `path` column is helpful.

**Comment by fuzzball5000** [comment]
Whilst not a problem we are facing currently (we are managing our configuration using other tools) it's an interesting problem. 

Rather than writing code to rummage around within config files for specific directives, which as you suggested would be difficult to fully achieve, a function to diff an entire file and compare that to some single "gold" version hosted in some definitive location would probably be straightforward enough to do. 

In the example you gave, I would expect sshd.conf within a managed environment to be a fairly singular and controlled entity (or if not, you would have a configuration which you considered to be "ideal", and would like to know on which of your hosts this configuration exists). Therefore a table which diffs the file specified in target_path to a remotely hosted version (which could be checked out each time the query is ran, and then discarded) and then logs "added" and "removed" events for each +/- entry in the diff accordingly may meet your needs?

**Comment by theopolis** [comment]
If you're running Chef or Puppet and have the ability to pull a "gold" then the cookbook managing the SSHd service should just overwrite the local changes. :)

Using osquery as a [file integrity monitor](http://osquery.readthedocs.io/en/stable/deployment/file-integrity-monitoring/) to detect/hash local unmanaged changes is what I do currently. For almost everything in `/etc/`, if you view/`group by` the hashes across infrastructures you can easily see anomalous hosts. If I compare that to Chef logs then I can raise signal around which hosts are "actively" using different configurations. If you don't do this then the seemingly-anomalous hosts may have Chef/Puppets or something else making them unhealthy.

The last step to "automated" FIM would be pulling the files, or differentials, for those hosts appearing actively anomalous. I like your idea, observing the changes via the osquery-normal tabular view works. But I can't help feel like it's the hammer approach and we can do better. But I can't figure out how without some backend automation, something that instructs the host to pull a file. This is because the anomaly detection happens within the backend aggregation, the host normally does not know if it is action anomalous-- since configuration changes are 99% expected.

Something like [Zentral](https://github.com/zentralopensource/zentral), [doorman](https://github.com/mwielgoszewski/doorman), or [Kolide](https://github.com/mephux/kolide) might be the place to add this.

**Comment by fuzzball5000** [comment]
Agree, the backend automation required to pull a "gold" file for comparison would probably be extending the functionality of the project unnecessarily, just struck me as an interesting problem to think over in the context of the implied restrictions in the OP's post. As I say, we use config management so we already have this capability. 

To your last point, yes, and the data gathered by well chosen OSQuery queries can be used to frame and contextualise FIM events at aggregation time very well, it's the method I'm using with Splunk to "trim" the risk scores applied to FIM alerts.

**Comment by apfelwerk** [comment]
actually in zentral we have "tags" you can attach to "probes" - a probe is a bundle of metadata, filters, osquery and some actions - in discussed case here - if a osquery result returns events to a probe there's an action type to set a "new tag" which automatically can activate additional probe(s) - so that way we use "automated" FIM already

**Comment by jamespo** [comment]
Regarding parsing configuration files, there is the Augeas project

http://augeas.net/docs/references/lenses/files/sshd-aug.html

**Comment by theopolis** [comment]
Hi all, we have this feature now using `augeas`. The virtual table isn't complete or included in a stable release (and we can definitely use more testers / criticism on how it's implemented), but I'm going to close this issue.

Please open subsequent issues for proposed changes in how the `augeas` table is implemented, and thanks for your patience!

**Comment by fuzzball5000** [comment]
Great work, thanks :)
