### ISSUE TITLE
Add journald logger

### ISSUE THREAD

**Issue by thedrow** [facebook/osquery#2190]
journald is part of the systemd stack and is widely used for system logging and log forwarding.
I think we should add a logger plugin for it.

**Comment by theopolis** [comment]
/cc @zwass 

I'm not sure if we should instrument journald when we have a syslog pipe. I'm vastly uneducated when it comes to systemd, but isn't your system's syslog a downstream receiver of journald output? Perhaps there is more structured data when instrumenting at the journald level?

**Comment by thedrow** [comment]
Yes, syslog, kmsg, console or file are downstreams of journald output.
Generally speaking, when running under systemd you shouldn't manage logging at all. You should just output to console and let journald handle the messages.
I'm not sure if that's the case with OSQuery though.

**Comment by zwass** [comment]
Users of this output plugin and the syslog table would have to be careful not to end up with exponentially exploding logs as output flowed in an infinite loop through osquery. Neither this output plugin, nor the syslog table are active by default, so there would likely be a way to shortcut this. If the appropriate facility/tag were applied to the output to syslog, the rsyslog rule used to ingest into osquery could filter out that particular facility/tag. I'm not familiar with journald, but because it claims to be more structured than standard syslog, I imagine this would be possible. It would still require careful configuration by a user running both the syslog table and the journald output plugin.

**Comment by theopolis** [comment]
Do we still need this?

**Comment by thedrow** [comment]
It's just an idea. If you think it won't be implemented by anyone feel free to close this issue.

**Comment by groob** [comment]
I implemented logging to journald as an extension [here](
https://github.com/kolide/go-extension-tutorial/blob/ad201cb14a3ff7d7328ca5f8f66a9b0bfb81ae47/pkg/journal/journal.go)

IMO it’s not worth adding more loggers to core, especially if they won’t be enabled by most osquery users. They’re very easy to create as extensions but end up being a maintenance burden.

**Comment by thedrow** [comment]
So should we close this issue?

**Comment by groob** [comment]
IMO yes, if someone believes this should be in core, the issue can be re-opened. 
If anyone needs help setting up the journald logger extension I linked above, feel free to @groob in the comments :)
