### ISSUE TITLE
`make deps` can't install pip

### ISSUE THREAD

**Issue by defaultnamehere** [facebook/osquery#2323]
When running `make deps` inside an Ubuntu 16.04 Docker container, the pipeline stops on the following error message:
```
/usr/local/osquery/Cellar/libdpkg/1.18.9: 51 files, 3.2M
[+] upgrading pip and installing python dependencies
Traceback (most recent call last):
  File "/usr/local/osquery/bin/pip", line 5, in <module>
    from pkg_resources import load_entry_point
ImportError: No module named pkg_resources
Makefile:98: recipe for target 'deps' failed
make: *** [deps] Error 1
```

The problem is that osquery's custom pip executable (located at `/usr/local/osquery/bin/pip`) can't see pkg_resources (located at `./Cellar/python/2.7.12/libexec/pip/build/lib/pip/_vendor/pkg_resources`). 
Is this a bug, or am I missing something?

**Comment by hackgnar** [comment]
There was a recent change with the build process.  The docs for those changes can be found here:
https://github.com/facebook/osquery/issues/2253

For now, use `OSQUERY_BUILD_DEPS=1 make deps` for ubuntu 16.04 and you will be good.

**Comment by artemdinaburg** [comment]
I also ran into this and I have a solution for you, works on OSX El Cap and Ubuntu 14.04.  I don't know the root cause of the error, although it looks like `distribute` and `pip` are not properly installed for the brew-installed python. My solution is kind of awful, I'm sure there's a better way.

Here goes:

-  `wget https://svn.apache.org/repos/asf/oodt/tools/oodtsite.publisher/trunk/distribute_setup.py`
-  Edit `distribute_setup.py`. After the initial imports, paste this code to get rid of SSL certificate validation errors (yes this is awful):  
```
import ssl

ssl._create_default_https_context = ssl._create_unverified_context
```
-  `/usr/local/osquery/bin/python ./distribute_setup.py`
-  Edit `/usr/local/osquery/bin/easy_install`. Again, after the imports paste in the (awful) chunk to disable SSL validation:
```
import ssl

ssl._create_default_https_context = ssl._create_unverified_context
```
-  `/usr/local/osquery/bin/easy_install -U pip`
-  Re-run `make deps`. 

After this the `make deps` process should make it past the Python failures.

**Comment by theopolis** [comment]
Can you try:
```
git pull
make depsclean
make deps
```

**Comment by defaultnamehere** [comment]
Yep, works for me =]
Thanks!
