### ISSUE TITLE
Table request: sudoers

### ISSUE THREAD

**Issue by arubdesu** [facebook/osquery#2396]
As per this POC extension,  https://gist.github.com/arubdesu/65729a232324c2905c0e2f357de7733e sudoers would be useful to include as a table based on the 'header' (first field in a config line) and 'rule_details' (rest of line). This enables compliance recommendation documents like the CIS for macOS to return details like an altered config that disables the 5-minute grace period. 

For other POSIX platforms there may be more meaning attached to each section or different naming requested, so there is a [previous revision](https://gist.github.com/arubdesu/65729a232324c2905c0e2f357de7733e/2efc5859df622fad123ae9e7d2103f41bdee6b9e) (now with less lambdas!) that could be modified to bring about those different designations.

**Comment by theopolis** [comment]
For those playing Hacktoberfest, here's a brief intro to get you started:
1. Development for osquery is best done on OS X 10.11, Ubuntu, CentOS (please excuse us while we refresh the build tooling for 10.12)
2. Follow the 4 instructions here on your host or check out the `vagrant` boxes provided: http://osquery.readthedocs.io/en/stable/development/building/#building-on-os-x
3. Check out the new table walkthrough here: http://osquery.readthedocs.io/en/stable/development/creating-tables/#new-table-walkthrough

For this table, since it's applicable to both Linux and OS X, the `spec` should go into `./specs/posix` and the implementation should go into `./osquery/tables/system/posix`.

**Comment by vjon** [comment]
This issue should have been closed by PR #2686, merged Nov. 12th, 2016
