### ISSUE TITLE
Using distribution packages instead of linuxbrew?

### ISSUE THREAD

**Issue by trizt** [facebook/osquery#2602]
I have not yet begun, but just spent a bit of thought on how to make an ebuild of osquery and I have to say that the linuxbrew way don't feel optimal at all, as it causes quite a lot of download and it will most likely not be approved into the portage, even if you get it to install all the files within the sandboxed build environment, as you would be downloading a lot of files each time you upgraded osquery.

Are there any unofficial make files to build this against those libraries which are provided by the OS instead of using linuxbrew?

**Comment by theopolis** [comment]
Right, unfortunately for us, our build tooling gives a false sense of automation for packagers / distro maintainers.

The answer is not really, and we don't have a good method of separating out our dependency-enabled features as you'd expect from `autoconf` or `cmake` options. If you pretend our build tooling doesn't exist that means a LOT of work for a packager because we're depending on "newish" and usually-not-available libraries: RocksDB, aws-sdk-cpp, snappy, libaptpkg, libdpkg, google-benchmark, asio (non-boost), cpp-netlib.

In a better world we'd gate these features in `cmake`. I empathize deeply with how frustrating that can be.

At the same time, I'm enthusiastic to help with `cmake` code reviews for anyone wanting to spearhead the compartmentalization of our dependent features. It will lead to potential fragmentation in feature sets across distributions but off the top of my head the only areas of concern are:

* `sleuthkit`-enabled virtual tables
* `yara`-enabled virtual tables
* `rpm` (librpm)-enabled virtual tables
* `tls` configuration and logger plugins
* `rocksdb` as a backing store

Also worth nothing, the ELFs in our rpm and deb-based distributions should work on any 2011+ Linux distribution. I can edit our downloads page to provide a `.tgz` that can be extracted into your prefix of choice (or two `.tgz` one for upstart, the other for systemd).

**Comment by trizt** [comment]
At the moment I'm concentrating on adding support for portage related tables, but I have noticed that the linuxbrew fails on one of my machines with failing with setuptools installation, as I already have the majority of the dependencies (a few missing) on the system, it had been easier to just make ebuilds for the missing libraries than really figure out what really goes wrong with linuxbrew (at least for me).

Sure there are a number of ebuilds in Gentoo with rpm/deb as source file, but as a long time Gentoo user, it always feels better when you can build it yourself. As the ebuild itself is at the moment a bit secondary and if the official builds would in the future support gentoo portage related tables, then of course using the binaries would be an option.

Another question, I saw there are some code which was prepared which would make centos related stuff only build on centos/redhat machines and ubuntu related stuff only on ubuntu build machines, is that they way osquery will be heading or that deprecated out-commented code?

**Comment by theopolis** [comment]
Right, the Linux distribution-specific tables are legacy. It's much easier to test/support a uniform set of tables for all of Linux. :)

**Comment by trizt** [comment]
Thanks, then I'll remove some out-commented code I put there as I thought I was future proofing my implementation.

**Comment by theopolis** [comment]
:+1:
