### ISSUE TITLE
Bundle curl PEM into packages

### ISSUE THREAD

**Issue by marpaia** [facebook/osquery#2850]
<img width="549" alt="task" src="https://cloud.githubusercontent.com/assets/927168/20981548/0755e37e-bc6a-11e6-855a-5879f6f93dfb.PNG">

**Comment by theopolis** [comment]
The cURL project provides an updated PEM bundle-- and that is installed with osquery's `make deps` into `/usr/local/osquery/etc/openssl`. This is used internally with the build and dependency management system to fetch resources over TLS.

Since osquery's `openssl` is statically linked we cannot assume the target hosts will have OpenSSL-provided bundles for TLS validation. We have previously recommended including the TLS server leaf or intermediate/root certificates within the deploy if folks are using the TLS plugins.

If we provide a copy of cURL's bundle we can relax that requirement.

**Comment by marpaia** [comment]
Should we keep this open until we are including the certificate bundle at `C:\ProgramData\osquery\certs\certs.pem`?
