### ISSUE TITLE
Compile for 32 bit

### ISSUE THREAD

**Issue by csark** [facebook/osquery#2856]
I am not super deep on the development side of osquery or other tools for that matter, but what prohibits this project from being compiled for 32 bit systems? I am just wondering as our company has myriad ancient 32 bit linux systems that cannot be retired. The systems meet the library requirements and it would be awesome to get more visibility into these machines with osquery as other modern tools are not able to run on these systems either.

**Comment by cark2** [comment]
PM me for solution.

**Comment by csark** [comment]
Who am I supposed to PM?

**Comment by theopolis** [comment]
The issue is largely time vs. impact. There are about 20 dependencies that are statically linked, we control the build for those so we'd have to refactor several recipes to make sure each built using a 32bit runtime. Then we'd have to scour the osquery codebase for structures and alias types that assume 64bit ints. That step isn't magic, the compiler flags are very strict so every occurrence will make it self known for 99% of the code. Finally we'd have to alter the build and CI to include testing on 32bit hosts.

For that to happen someone knowledgeable and excited will need to invest themselves in the codebase. The current development does not have any 32bit targets we need to manage so it's outside of our scope. We're always willing to do code reviews and discuss with someone who wants to join though.

**Comment by csark** [comment]
Thanks for the feedback Teddy. I assumed it was something like you described.
