### ISSUE TITLE
deps: Need glibc mirror

### ISSUE THREAD

**Issue by theopolis** [facebook/osquery#2881]
Dependencies rebuilds are failing due to a network issue with: https://ftp.heanet.ie/mirrors/gnu/glibc/glibc-2.19.tar.bz2

**Comment by vjon** [comment]
Is there any particular reason we didn't use GNU's own FTP server instead of an external mirror in the first place?

Also, if I'm understanding correctly, we're simply looking to replace the `heapnet` mirror URL entirely, correct? That is, we're NOT necessarily interested in implementing a secondary URL for the provision script to fall-back on in the event of network issues with a primary URL?
