### ISSUE TITLE
Question on Building from source 

### ISSUE THREAD

**Issue by kravivar** [facebook/osquery#2959]
Hello,

I`ve trying to build the osquery from source for coreos and everytime I build the library it takes atleast 40 to 45 mins to complete.

Is there a way I could speed up the build process ?

Steps that I follow,

```
mkdir -p temp
sudo chown -R $USER. temp
cd temp
git clone https://github.com/facebook/osquery.git
cd osquery
make sysprep
make deps
make
make strip
```

Thanks,
Kripa

**Comment by PoppySeedPlehzr** [comment]
Overall, I'm not entirely positive why it would be taking you so long to build, but there's some small things you can do to at least speed up the `make` process. Try setting `SKIP_TESTS=1` as well as passing a `-j <Number>` values, so that your build command looks like:

`SKIP_TESTS=1 make -j 4`

Also, most of those steps should only take 1 pass, and iterating on building osquery should just be a matter of running the `make` command above.  Let me know if that helps out at all :)

**Comment by kravivar** [comment]
Thank you @PoppySeedPlehzr now the build time has drastically dropped to 15 mins. Is that the time that is expected.

**Comment by theopolis** [comment]
The `make sysprep` is the largest time-sink. That is making sure you have an updated OS, updated set of compiler toolchains, and all of the build dependencies. A developer workflow will require that, but usually as a 1-time operation :)
