### ISSUE TITLE
PermissionsTests.test_path_drop on Darwin as root is breaking

### ISSUE THREAD

**Issue by theopolis** [facebook/osquery#3192]
```
[ RUN      ] PermissionsTests.test_path_drop
/Users/osquery/jenkins/workspace/osqueryPullRequestOSX/TargetSystem/vm-osx12/osquery/core/tests/posix/permissions_tests.cpp:95: Failure
Value of: dropper->dropTo(getuid(), getgid())
  Actual: true
Expected: false
```

**Comment by theopolis** [comment]
@jedi22 did you see this in your testing? When run as `root`, this is the only test failing (out of the Permissions tests). Passing on Linux though ;)

**Comment by jedi22** [comment]
@theopolis I don't recall if I tested with root on OS X because I didn't think I was changing any of the code that affected it.

**Comment by jedi22** [comment]
This is the call that is causing test failures. It fails because we expect this to return False.

https://github.com/facebook/osquery/blob/65ef94f053df933bcb7324cc9efdb48bfd57bdea/osquery/core/system.cpp#L409

Changing this to true makes the test pass and the check after which is suppose to check that dropping permissions worked correctly also passes with no modifications. I think this is just a bad test.
