### ISSUE TITLE
windows: Add examples of Registry table queries

### ISSUE THREAD

**Issue by muffins** [facebook/osquery#3218]
Since the registry virtual table re-write (thanks @ryanheffernan!), the usage of the registry table has changed a little, and now would be a great time to add some example queries to the table spec to make jumping into the registry easy!

**Comment by Centurion89** [comment]
Specifically, it was really confusing to me which segments of the "path" should go in `key` vs. `path` columns. Not really intuitive off the bat, but super straightforward after seeing examples. Would also be useful to show globbing examples because many people may not even realize it's possible with this table

**Comment by muffins** [comment]
#3597 did a pretty solid job of addressing this. I'd say if folks are looking for good uses of the registry table, the table spec examples should be pretty sufficient. Feel free to either re-open or create a new task if there's any additional examples you think we should have!
