### ISSUE TITLE
ERROR: RocksDB: Too many open files in systemAccumulated background error counts

### ISSUE THREAD

**Issue by mime-frame** [facebook/osquery#3594]
**Overview**

We're seeing errors like the following:

```
"RocksDB: [ERROR] Waiting after background flush error: IO error: /var/osquery/osquery.db/061374.sst: Too many open files in systemAccumulated background error counts: 0"

"Rocksdb open failed (5:0) IO error: /var/osquery/osquery.db: Too many open files in system"
```
**Details**
- osquery v2.6.1
- macOS devices

**Comment by theopolis** [comment]
This system seems fairly stressed. I can check out Chef management to see if we do anything to increase the max number of open files across the macOS fleet, but applying the recommendations here: https://superuser.com/questions/302754/increase-the-maximum-number-of-open-file-descriptors-in-snow-leopard seems unwieldy since there's a different method for each OS.
