### ISSUE TITLE
Properly monitoring osqueryd 

### ISSUE THREAD

**Issue by jaredledvina** [facebook/osquery#3667]
Hi! I asked in the Slack room but, figured this might be easier to document a solid approach. I'm looking for a sane way to ensure that the `osqueryd` daemon is properly running. Currently, I'm utilizing Nagios's [`check_procs`](https://nagios-plugins.org/doc/man/check_procs.html) and ensuring that there's always two running process with the name `osqueryd` and alerting if that's not the fact. This is done with `/usr/lib64/nagios/plugins/check_procs -c 2:2 -C osqueryd`:
```
# /usr/lib64/nagios/plugins/check_procs -c 2:2 -C osqueryd
PROCS OK: 2 processes with command name 'osqueryd' | procs=2;;2:2;0;
```

### Environment:
* CentOS 6 and CentOS 7
* OSQuery 2.7.0 

`osquery.flags`:
```
--disable_audit=false
--audit_allow_config=true
--audit_persist=true
--audit_allow_sockets
--logger_plugin=syslog
--events_max=100000
--watchdog_memory_limit=350
--events_expiry=1
```

### Questions:
1. Is the above approach accurate? Or are there cases where `osqueryd` is functioning properly and running more or less `osqueryd` daemons? If so, do you know what the upper and lower bounds are?
2. `check_procs` is as basic of a monitoring story as I could setup. Are there suggested alternative ways to monitor the daemon ensuring that it's actually working?

**Comment by Centurion89** [comment]
@jaredledvina I brought this up in today's officehours VTC and one other idea that came up was having a "heartbeat" query that runs on a periodic basis and checking on the backend logging system for the existence of the heartbeat and maybe correlating against a list of "known online" hosts.

**Comment by muffins** [comment]
So I think there's a few ways to do this, and I believe that internally we make use of just simple "heartbeat" queries similar to what @Centurion89 was describing, but it's all through osquery. As I mentioned in the office hours today, we recently started leveraging successful Chef runs and correlating this with osquery heartbeats to give us a picture/alert of "Is osquery running and ok?", so that might be another option.

I had an idea that I thought might be worth looking into, wherein you make use of one of the other plugin types to touch some form of heartbeat artifact on the file system to give indication that both worker and watcher are alive. Is this a good idea? This might've helped us identify more rapidly that the daemon was crashing on Windows, but I'm not sure if there'd be better designs for this or not.

**Comment by jaredledvina** [comment]
Adding some notes from the Slack conversation.
* If watchdog kicks in, it will kill the worker process **only** which can result in a single `osqueryd` process for a few seconds before it's restarted automatically. When this happens, the message `System performance limits exceeded` should be logged (Looking at https://github.com/facebook/osquery/issues/3604 though, it appears it currently might not be). The restart should take between 3-6 seconds. 

I like the idea of setting up a watch file that something updates/touches, and then ensuring that the event lands in `local3` (since we have the `--logger_plugin=syslog` flag set). The other idea I have is utilizing the query: 
```
    "filebeat_keepalive":{
      "query": "SELECT total_seconds FROM uptime;",
      "interval": 180
    },
```
and ensuring that we get a `filebeat_keepalive` event as well. That all said, getting a Nagios check to watch `local3` for the events doesn't sound fun.

**Comment by juju4** [comment]
Puppet (agent) also have an option to "ensure" service is in "running" state.

Current systemd config has already
```
Restart=on-failure
```

In my case, I also have monit rules to ensure it is running, binary and config present

**Comment by theopolis** [comment]
Thanks for all the discussion here! I'm going to close this out, if we still need investigation we can reopen :)
