### ISSUE TITLE
Windows: osqueryd "--install" switch creates pathless service, doesn't run

### ISSUE THREAD

**Issue by straffin** [facebook/osquery#3949]
Running `osqueryd.exe --install` creates an "osqueryd" service with an ImagePath of `osqueryd.exe --flagfile=\ProgramData\osquery\osquery.flags` which then fails due to osqueryd.exe not being in the path. 
Installing via chocolatey with the `--params='/InstallService'` flag creates a service with an ImagePath of `C:\ProgramData\osquery\osqueryd\osqueryd.exe --flagfile=\ProgramData\osquery\osquery.flags` which runs successfully. 
`osqueryd.exe --install` should either add osqueryd.exe to the path or (better) create the ImagePath with the fill path to osqueryd.exe intact.

**Comment by muffins** [comment]
Yeah, in order to use the `osqueryd.exe --install` you need to invoke it via the full path, as the logic gets the invocation path used to pass to the service create, so you'd need to run `C:\Path\To\osqueryd.exe --install` in order for the service installation to work correctly, but we can definitely do better and have this information be derived!

**Comment by straffin** [comment]
Thank you. Looking back at the documentation, it *does* list the full path, but does not indicate that using the full path is necessary. Might be a worthwhile addition. 😃

**Comment by muffins** [comment]
@straffin definitely, let's go ahead and leave this open as a reminder to fix up either the docs or the behavior itself. That's definitely a UX imo, and merits a PR to fix that experience :)

**Comment by muffins** [comment]
Addressed in #4316
