### ISSUE TITLE
Identify Linux servers that require Spectre/Meltdown upgrade

### ISSUE THREAD

**Issue by rodionos** [facebook/osquery#4026]
Service Providers started releasing [notes](https://wiki.hetzner.de/index.php/Spectre_and_Meltdown/en) on Spectre and Meltdown issues. 

It's early in the process, however is there a way using osquery to check if these attacks have taken place?

**Comment by mtmcgrew** [comment]
HI rodionos,

You've got a couple different questions in there.

1) Identifying servers that need the upgrade

This depends slightly based on distribution. For example, for RHEL the update is in the form of a kernel update along with other various packages (see the "Resolve" tab of https://access.redhat.com/security/vulnerabilities/speculativeexecution). In order to see if these updates have been applied you would be able to use the `kernel_info` and/or the `rpm_packages` table.

2) Identifying if the attacks have taken place

This is more tricky, if at all possible. On the meltdownattack.com website they even say that detection in unlikely as "the exploitation does not leave any traces in traditional log files". In my opinion, the best bet would be to try to detect some type of attacker activity after the exploitation, but that will vary depending on usage of the exploit and is hard to know what it will look like beforehand. I don't think anyone has a good way to detect this right now.

**Comment by rodionos** [comment]
Hello @mtmcgrew,

Using [RHEL 6](https://access.redhat.com/errata/RHSA-2018:0008) as an example, the system should be considered patched if the list of installed kernel packages includes the package **2.6.32** with version **696.18.7.el6**.

Translating this to osquery statement:

```sql
SELECT * FROM rpm_packages WHERE name = 'kernel' 
  AND version = '2.6.32' AND release = '696.18.7.el6';
```

```sql
+--------+---------+--------------+------------------------------------+-----------+------------------------------------------+--------+
| name   | version | release      | source                             | size      | sha1                                     | arch   |
+--------+---------+--------------+------------------------------------+-----------+------------------------------------------+--------+
| kernel | 2.6.32  | 696.18.7.el6 | kernel-2.6.32-696.18.7.el6.src.rpm | 137563269 | 10f9d1189ab8f69115189e961478eb55b92cf9e7 | x86_64 |
+--------+---------+--------------+------------------------------------+-----------+------------------------------------------+--------+
```

Alternatively, count=0 for the following query means the RHEL 6 server is **not** patched:

```sql
SELECT COUNT(name) FROM rpm_packages WHERE name = 'kernel' 
  AND version = '2.6.32' AND release = '696.18.7.el6';
```

For RHEL 7 the package versions and releases are different 3.10.0/693.11.6.el7, 3.10.0/514.36.5.el7, etc.

Would it be correct to proceed by building the list of releases (regardless of version) and run the following query?

```sql
SELECT COUNT(name) FROM rpm_packages WHERE name = 'kernel' 
  AND release IN ('696.18.7.el6', '693.11.6.el7', '514.36.5.el7');
```

Unpatched systems will be returning 0.

**Comment by rodionos** [comment]
[perf counters](https://www.endgame.com/blog/technical-blog/detecting-spectre-and-meltdown-using-hardware-performance-counters) approach to detecting abnormal cache flushes, as posted on HN. This would not give a definitive answer though and the information is not exposed to osquery.

**Comment by juju4** [comment]
Capsule 8 made some nice blog post on possible detection with memory page faults or cpu performance info (load/load miss cache)
https://capsule8.com/blog/detecting-meltdown-using-capsule8/
https://capsule8.com/blog/detecting-meltdown-spectre-detecting-cache-side-channels/

I asked if something similar would be implemented in opensource monitoring tools like telegraf or netdata but that's need new subsystem and contributions.
