### ISSUE TITLE
Scheduled Tasks - Removed/Added when Next Run changes

### ISSUE THREAD

**Issue by defensivedepth** [facebook/osquery#4270]
osquery 2.11.12 on Windows Server 2012 R2 & Server 2016. Kolide Fleet 1.06 for distributed queries.

Currently running the following query on the Windows servers every 60 min:

`SELECT * FROM scheduled_tasks`

It appears to be pulling in the scheduled tasks just fine, however, a subset of the scheduled tasks are being Removed & Added every time this query is run, even though these scheduled tasks are not be deleted/added back in. See the following screenshot: https://snag.gy/usUbtV.jpg

Digging into it deeper, it appears this subset of scheduled tasks have one thing in common: the Next Run Time has changed.... either because the task ran, and it is scheduled to run again, or the Next Run Time has a random offset that changes regularly, etc. See the following:  https://snag.gy/bnZx0P.jpg

It appears that osquery views this change as trigger that the task was Removed, and a new one Added.

Is this expected behavior?

**Comment by muffins** [comment]
Ah yeah, the current implementation of our differential queries will see that as a different result. The way you’d get around this behavior is avoid using ‘select * ...’ queries and be very specific about what data your want to see having changed for differential mode, and then leverage a snapshot query to get the “show me everything every time” data. I’m going to close this issue out as this is expected behavior, though possibly a little counter intuitive ;), but please feel free to re-open if you’d like!

**Comment by muffins** [comment]
Just to add onto that thought, a better differential query might be something like:
```
select name, action, path, enabled, hidden from scheduled_tasks;
```
for a security detection query, and then something like:
```
select name, action, last_run_time, last_run_message, last_run_code from scheduled_tasks where enabled=1;
```
As a `snapshot=true` query for sysadmin purposes.

**Comment by defensivedepth** [comment]
Thanks @muffins. It makes sense to be as specific as possible for differentials. 

It would be helpful if stuff like this were documented for each table - ie a Notes section were added to the tables documentation, and something like this:

**Notes**
State changes in the following columns will cause differential queries to flag the task as Removed / Added.
next_run_time

Thoughts?
