### ISSUE TITLE
Linux builds huge binaries

### ISSUE THREAD

**Issue by ErikGoldman** [facebook/osquery#4292]
hello! I'm building OSQuery on Ubuntu Xenial using the following commands:

```
git clone https://github.com/facebook/osquery
git checkout 360f58887c8b8084ea7447c5b8dbf2b04d29c01b
make depsclean && make sysprep && make deps && make
du -h build/linux/osquery/osquery*
```

result:

```
172M	build/linux/osquery/osquery_additional_tests
158M	build/linux/osquery/osquery_benchmarks
159M	build/linux/osquery/osqueryd
159M	build/linux/osquery/osqueryi
162M	build/linux/osquery/osquery_tables_tests
40M	build/linux/osquery/osquery_tests
```

159M! am I doing something wrong?

**Comment by fmanco** [comment]
Hi @ErikGoldman no you're not. Those binaries include all debug information. Our scripts automatically strip that out when creating packages and that's why if you install a .deb or .rpm the binary is so much smaller. You can strip the binary yourself running something like: `strip build/linux/osquery/osqueryd`.

Hope this helps.

**Comment by ErikGoldman** [comment]
ahh much better. thank you!
