### ISSUE TITLE
OSQuery SDK API example code

### ISSUE THREAD

**Issue by cheizer** [facebook/osquery#4450]
It appears that there is no c++ example code on using the libosquery.a library. 

I'm looking for the basics on embedding the libosquery.a and running basic queries on the core tables.

Thanks!

**Comment by muffins** [comment]
Ah, this is a feature that isn't exactly supported, and something we're not likely to support in the future. If folks are interested in making this happen that'd be cool, but it's a difficult path and we might not be able to help much. I'd say the best path for trying to land this would be to start a conversation in Slack and see if there's anyone who's done this who might be able to help.

Currently our only supported use of the osquery SDK is extensions, which are documented pretty well. You might start by building out an example extension, and see if you can get things up and running, and then start investigating the components you needed to change the state of in order to interact with osquery directly, and not over the thrift extensions socket.

I'm going to close this out for now as I mentioned it's not something we're currently looking to support. But feel free to re-open if you'd like to continue the conversation -- that being said I think Slack #core might be a better medium for talking about this :)
