### ISSUE TITLE
compatibility with CentOS 5 and glibc 2.5

### ISSUE THREAD

**Issue by captainbupt** [facebook/osquery#4462]
### What version of `osquery` are you using? What operating system. Be specific.
I was trying to install osquery in our company's machines. However, half of machine are running on CentOS 5 with glibc 2.5.  When I execute `osqueryd`, the following error comes up, as expected.

```
./osqueryd: /lib64/libc.so.6: version `GLIBC_2.6' not found (required by ./osqueryd)
./osqueryd: /lib64/libc.so.6: version `GLIBC_2.7' not found (required by ./osqueryd)
./osqueryd: /lib64/libc.so.6: version `GLIBC_2.8' not found (required by ./osqueryd)
./osqueryd: /lib64/libc.so.6: version `GLIBC_2.9' not found (required by ./osqueryd)
./osqueryd: /lib64/libc.so.6: version `GLIBC_2.10' not found (required by ./osqueryd)
./osqueryd: /lib64/libpthread.so.0: version `GLIBC_2.12' not found (required by ./osqueryd)
```

### What have you already tried?
It is not feasible to upgrade OS for all machine. Trying to install higher version of glibc, but all ends up with compilation error. From some forum, it seems that it is a bad idea to upgrade glibc on CentOS 5

I was thinking if osquery really need some new features in higher glibc and if it is possible to modified osquery to be compatible with glibc 2.5. 

So, what's your opinion on such case? Thanks a lot!

**Comment by muffins** [comment]
From an initial gut reaction - we don't support CentOS 5 :( The only machines we support are those listed in the `README.md` on the repo with Jenkins build jobs. As for whether or not we could make the move to have our build system be compatible with glibc 2.5, @theopolis might be able to offer some insight as I know he's probably the closest to the build system at this point.

**Comment by theopolis** [comment]
Right, we require glibc 2.12+

This is mostly because we have lots of dependencies and would need to build/link them all against and old glibc, this means lots of nuances for build expectations in build logic we do not maintain. Sorry about this, if there's an extremely powerful use-case we can try to help.

If you would like to deep-dive into checking feasibility and making this work, go here: https://osquery.readthedocs.io/en/stable/development/building/#dependencies-and-build-internals

Then experiment with a 2.5 version of glibc here: https://github.com/facebook/osquery/blob/master/tools/provision/formula/glibc-legacy.rb#L7 

Essentially if you modify that version, you can slog your way through the entire toolchain build with:
`DEBUG=1 make build_deps`
