### ISSUE TITLE
Unable to install osqueryd service

### ISSUE THREAD

**Issue by CR1AT0RS** [facebook/osquery#4639]
I am getting this error when trying to install osquery as service in Windows server 2016.

**
C:\ProgramData\osquery\osqueryd\osqueryd.exe --install
> E0625 12:59:41.417889  2144 main.cpp:154] Unable to install the osqueryd service

**
OS: Windows Server 2016 standard.
Installed the service using Chocolate.

Any ideas ?

**Comment by muffins** [comment]
@CR1AT0RS you can use `choco install osquery --params='/InstallService'` to have chocolatey install it for you, otherwise you should be able to install via what you've shown, `C:\ProgramData\osquery\osqueryd\osqueryd.exe --install`. Are you running as an Administrative command prompt? This issue might better be triaged in [our Slack](https://osquery-slack.herokuapp.com/), Checkout the windows channel :) I'm going to close this issue out, as we should move our discussion there before cutting the issue, thanks!
