### ISSUE TITLE
Intermittent crash exiting `osquery_tests` on Linux

### ISSUE THREAD

**Issue by jkeljo** [facebook/osquery#5195]
# Bug report

### What operating system and version are you using?

```version = 14.04.5 LTS, Trusty Tahr
   build = 
platform = ubuntu
```

### What version of osquery are you using?

2ddd10b3

### What steps did you take to reproduce the issue?
`make debug`
`build/debug_linux/osquery/osquery_tests`

### What did you expect to see?
All successful tests

### What did you see instead?
All successful tests, then one of the following:

```
*** Error in `build/debug_linux/osquery/osquery_tests': corrupted size vs. prev_size: 0x0000000001c616e0 ***
Aborted (core dumped)
```

OR

```
Segmentation fault (core dumped)
```

**Comment by jkeljo** [comment]
Looked into this, and it appears to be a static destruction order thing, between `Dispatcher` and `BufferedLogSink`. (The former tries to log in its destructor, and if the latter has already been destroyed things do not go well.)

I suppose the ideal fix would be to more gracefully disable logging before destroying the sink, but I suspect this is unique to the testing environment, so I'm not really sure. I did verify that just leaking the `BufferedLogSink` makes the problem go away.

**Comment by guliashvili** [comment]
#5192  was supposed to 'resolve' this problem. 

I tested 2ddd10b3df1db770a5cee96ca7c9a96b6e5d2e95 in vagrant ubuntu16.04 vmware image -  `make debug && make test_debug `also `make && make test` and things work fine.
Would you mind checking that #5192 is landed in your codebase?

To be honest, graceful shutdown is our problem. It will have to be fixed sooner or later. Because we have so many singletons, putting things in their destructors is not so safe(one example dispatcher). I suppose the fix you mentioned, would also have to be implemented inside the destructor of another singleton class. :( Or else we would need some bolder changes.

**Comment by jkeljo** [comment]
Yeah, looks good.
