### ISSUE TITLE
Create a standard for mocking system calls for unit testing virtual tables

### ISSUE THREAD

**Issue by zwass** [facebook/osquery#580]
Many virtual tables rely on system calls to retrieve their data. Having a standard for how to mock these system calls and unit test the virtual table functions would be very helpful.

**Comment by marpaia** [comment]
I think system calls is a bit of a misnomer here, since what we really want to wrap are miscellaneous C APIs on OS X and Linux, not necessarily POSIX syscalls. We need to step up our mocks game, I view this as a part of that larger effort. I'm going to close this now, but we should still be thinking about how to make our tests better (we always should be).
