### ISSUE TITLE
osqueryctl tool

### ISSUE THREAD

**Issue by marpaia** [facebook/osquery#585]
We need to create an osqueryctl tool which will abstract some osquery administration tasks. Such tasks may include:

- enable
- disable
- config-check
- status
- info

**Comment by maus-** [comment]
I have an init script that more or less provides this without a whole new binary that might be useful. Just remove the ERB nonsense

https://github.com/maus-/osquery-cookbook/blob/master/chef/cookbooks/osquery/templates/default/osquery.erb

**Comment by theopolis** [comment]
@maus- I like that a lot, and you should be able to `--daemonize` now on Linux (OSX should use LD).

I think a simple `osqueryctl` script to provide stats and help "install" the LaunchDaemon on OSX after we write the plist to /var/osquery/com.facebook.osqueryd.plist is needed. Since we want to support managing the LD plist through orchestration we don't want the package to clobber an existing LD plist, but rather use the ctl script to write a symlink if none exists. Then if you write over the symlink in `/Library/LaunchDaemons/` newer osquery installs will honor your customizations.

The `osqueryctl` could also symlink the `/var/osquery/osquery.conf` to someplace in /etc on Linux for similar forwards-customization-compatibility. 

We should definitely install a init script on Linux with the DEB/RPM distributions similar to the LD on OSX. We're in a much better place with an init script since they aren't customized and are enabled/disabled by the administrator. A LD will start on reboot unless you edit the plist. So in the Linux case we don't need an enable/disable.

A config-check is very helpful and status/info are good starting points for some other helpful functions we'd like to include in this script.

**Comment by marpaia** [comment]
being addressed in #791
