### ISSUE TITLE
Enhancement request for the hash table

### ISSUE THREAD

**Issue by ed-sfdc** [facebook/osquery#616]
Hash algorithms - MD5 and Sha256
Use of wild cards in directory field - We would like to be able to use wild cards in the directory.  For example, If I used '/tmp/%' I'd like to get the hash of all files in '/tmp' and all files inside of various folders.  Another example if I used '/Users/%/Downloads/%' I'd be able to get the hash of all files in every users Downloads folder.  
Use of wild cards in path field or new field for file name - Not sure if a new field or doing a join on the file and hash table is better for performance.  Looking for a way to identify if there are multiple files of the same name installed on the system.  For example, bash is in '/bin/bash' and '/tmp/bash'.  The wild card would be something like '%/bash'.  This also might be something we could do in splunk, but we haven't gone there yet.

**Comment by theopolis** [comment]
100% agree!

**Comment by theopolis** [comment]
Trying to find filename (base name from path) collisions by path/directory traversal is a bad idea the way we have traversal implemented. ;)

I'm going to experiment with a few features here and see how performant they are:
1. Extend the QueryContext constraints operators to include "MATCH" which will allow the match-all LIKE-style where clause expressions.
2a. Dig through boost to find optimization for filesystem + regex path matching.
2b. Dig through mfind/mds APIs as a regex matching alternative to boost.
3. Add some sha- family algorithms to hash and measure the inner join performance with file.

**Comment by theopolis** [comment]
The match operators are the set of infix functions: LIKE/GLOB/REGEX. To support them we'll need to add the SQLite `xFindFunction` module and come up with an architecture for passing the function request to the virtual table implementation. Since you'll want to apply the output of the function as if it were a predicate constraint.

**Comment by marpaia** [comment]
Do LIKE constraints not show up in QueryContext now?

**Comment by theopolis** [comment]
The infix functions are not treated as conditional operands with a virtual table parsable expression by SQLite. We'll need to detect their usage, grab the expressions and function then include it in the QueryContext somehow. I think we should represent them as constraints if they are in the where clause/predicate but we should treat the expressions as comparative with meaningful symbols for the REGEX/wildcarding.

**Comment by theopolis** [comment]
@jedi22 since infix operations are not appropriate at this time (requires some modding of SQLite's virtual table implementation and we have survived this long without any modifications to mainline), checkout RE2! 

https://code.google.com/p/re2/

Also: I just read some notes about locking problems with boost::regex, but if they are good enough to get the job done and building RE2 into our third-party is too much hassle, that's fine.

**Comment by theopolis** [comment]
I think we're gtg on this one pending gotchas from #722.
