### ISSUE TITLE
Security: Upgrade dependencies to latest versions

### ISSUE THREAD

**Issue by Jimjazzz** [facebook/osquery#7494]
# Feature request

### What new feature do you want?

Running a vulnerability scan via SNYK to osquery dependencies i got the following HIGH severity positives:

cryptsetup@1.7.5 
   CVE-2020-14382
     - https://nvd.nist.gov/vuln/detail/CVE-2020-14382
     - https://security.snyk.io/vuln/SNYK-UNMANAGED-CRYPTSETUPCRYPTSETUP-2374187

libgcrypt@1.8.1
   CVE-2018-6829
     - https://nvd.nist.gov/vuln/detail/CVE-2018-6829
     - https://security.snyk.io/vuln/SNYK-UNMANAGED-LIBGCRYPT-2374569
     
   CVE-2021-33560
     - https://nvd.nist.gov/vuln/detail/CVE-2021-33560
     - https://security.snyk.io/vuln/SNYK-UNMANAGED-LIBGCRYPT-2374558

  CVE-2021-3345
     - https://nvd.nist.gov/vuln/detail/CVE-2021-3345 
     - https://security.snyk.io/vuln/SNYK-UNMANAGED-LIBGCRYPT-2374567

util-linux@2.27.1
  CVE-2016-2779
     - https://nvd.nist.gov/vuln/detail/CVE-2016-2779
     - https://security.snyk.io/vuln/SNYK-UNMANAGED-UTILLINUX-2334960
  
  CVE-2018-7738
     - https://nvd.nist.gov/vuln/detail/CVE-2018-7738
     - https://security.snyk.io/vuln/SNYK-UNMANAGED-UTILLINUX-2334955
 
rpm@4.16.1.2
  CVE-2021-20271
    - https://nvd.nist.gov/vuln/detail/CVE-2021-20271
    - https://security.snyk.io/vuln/SNYK-UNMANAGED-RPMSOFTWAREMANAGEMENTRPM-2377258

All of them are fixed in newer versions of the dependencies.

I am not very expert with the tool so i am not sure how much of the positives apply but i think it could be a good idea to update the references to this submodules.

### How is this new feature useful?

Avoid vulnerabilities in the software

### How can this be implemented?

Upgrade dependencies to newer versions.

**Comment by Jimjazzz** [comment]
The previous run of the SNYK was in a windows server which cannot import all dependencies, running it in a Linux server raised more CRITICAL / HIGH alarms in systemd and lldpd dependencies :

systemd@174 - 3 CRITICAL 14 HIGH
  CVE-2020-1712
    - https://nvd.nist.gov/vuln/detail/CVE-2020-1712
    - https://security.snyk.io/vuln/SNYK-UNMANAGED-SYSTEMDSYSTEMD-2365493
  CVE-2017-1000082
    - https://nvd.nist.gov/vuln/detail/CVE-2017-1000082
    - https://security.snyk.io/vuln/SNYK-UNMANAGED-SYSTEMDSYSTEMD-2365470
  CVE-2018-20839  
    - https://nvd.nist.gov/vuln/detail/CVE-2018-20839
    - https://security.snyk.io/vuln/SNYK-UNMANAGED-SYSTEMDSYSTEMD-2365480
  CVE-2018-15688
    - https://nvd.nist.gov/vuln/detail/CVE-2018-15688
    - https://security.snyk.io/vuln/SNYK-UNMANAGED-SYSTEMDSYSTEMD-2365482
  CVE-2015-7510
    - https://nvd.nist.gov/vuln/detail/CVE-2015-7510
    - https://security.snyk.io/vuln/SNYK-UNMANAGED-SYSTEMDSYSTEMD-2365467
  CVE-2016-10156
    - https://nvd.nist.gov/vuln/detail/CVE-2016-10156
    - https://security.snyk.io/vuln/SNYK-UNMANAGED-SYSTEMDSYSTEMD-2365487
  CVE-2018-6954
    - https://nvd.nist.gov/vuln/detail/CVE-2018-6954
    - https://security.snyk.io/vuln/SNYK-UNMANAGED-SYSTEMDSYSTEMD-2365469
  CVE-2019-3843
    - https://nvd.nist.gov/vuln/detail/CVE-2019-3843
    - https://security.snyk.io/vuln/SNYK-UNMANAGED-SYSTEMDSYSTEMD-2365484
  CVE-2019-3844
    - https://nvd.nist.gov/vuln/detail/CVE-2019-3844
    - https://security.snyk.io/vuln/SNYK-UNMANAGED-SYSTEMDSYSTEMD-2365483

.... and more (i can get all the CVEs if it is something you guys want to see)

lldpd@0.9.6 - 1 HIGH
  CVE-2020-27827
    - https://nvd.nist.gov/vuln/detail/CVE-2020-27827
    - https://security.snyk.io/vuln/SNYK-UNMANAGED-VINCENTBERNATLLDPD-2366495

**Comment by Jimjazzz** [comment]
Hi, would you be able to let me know if the vulnerabilities detected are real security concerns? I would assume that as long as the dependency is included the risk of exploit is there, but i am not so sure if that is the case.

I think that the most concerning one is the systemd v174, as it includes 4 Critical and 16 High vulnerabilities according to SNYK. 

I am also attaching the full report for reference:
[snyk-report-2022-03-09T11_45_38.193Z.csv](https://github.com/osquery/osquery/files/8214526/snyk-report-2022-03-09T11_45_38.193Z.csv)

**Comment by zwass** [comment]
@Jimjazzz can you provide the command/configuration you used to run Snyk? I'm trying to reproduce these results and Snyk is not picking up nearly as much as what you've documented here.

**Comment by mike-myers-tob** [comment]
Milestone 5.3 with target date April 1 has been created: https://github.com/osquery/osquery/milestone/61

This will address immediate library updates, now opened in the following issues:

- [ ] https://github.com/osquery/osquery/issues/7510
- [ ] https://github.com/osquery/osquery/issues/7511
- [ ] https://github.com/osquery/osquery/issues/7512
- [x] Update OpenSSL was already done https://github.com/osquery/osquery/pull/7506

The following dependencies will be updated, but will not hold up the 5.3 release since they do not involve any CVEs that seem to impact osquery:

- [ ] https://github.com/osquery/osquery/issues/7513
- [ ] https://github.com/osquery/osquery/issues/7514
- [ ] https://github.com/osquery/osquery/issues/7515
- [ ] https://github.com/osquery/osquery/issues/7517
- [ ] https://github.com/osquery/osquery/issues/7518

**Comment by Jimjazzz** [comment]
@mike-myers-tob thanks for the update.

I was looking into all the issues that you have created to update and i cannot find the `systemd` one (libudev), which is the one that shows the most vulnerabilities. Does it mean that all the vulnerabilities reported for it do not affect osquery and there is no need to upgrade it from v174?

Thanks!

**Comment by mike-myers-tob** [comment]
> I was looking into all the issues that you have created to update and i cannot find the `systemd` one (libudev), which is the one that shows the most vulnerabilities. Does it mean that all the vulnerabilities reported for it do not affect osquery and there is no need to upgrade it from v174?
> 
> Thanks!

osquery doesn't include `systemd` so we have to determine how that is getting flagged in the scanner. osquery does use `libdbus` to communicate with the local `systemd` instance to enumerate the service units. If `systemd` is a transient dependency then whatever dependency include it will have to be updated.

**Comment by mike-myers-tob** [comment]
Ok, I just added https://github.com/osquery/osquery/issues/7527 to the release milestone

**Comment by mike-myers-tob** [comment]
Having investigated further, `libudev` uses a version of `libsystemd` with a commit ID that predates all of the CVEs in `systemd`, therefore scanners are flagging all CVEs since the beginning of `systemd` as affecting the library. So the scan report is apparently all false positives: all of these CVEs are on the `systemd` service, not the library. We've done our due diligence to look at each of the individual CVEs listed and determined they don't impact osquery, so we will not block osquery 5.3 on updating `libudev`.

**Comment by mike-myers-tob** [comment]
Adding this, not because it impacts osquery per se, but because it is highly visible and people with osquery deployments are urgently trying to avoid the problem: https://github.com/osquery/osquery/issues/7541

**Comment by mike-myers-tob** [comment]
From [the above list](https://github.com/osquery/osquery/issues/7494#issuecomment-1071083041) there's still a few more dependencies due to be updated, so I'll move this forward another milestone.

Additionally we are updating or have recently updated:

- [ ] https://github.com/osquery/osquery/pull/7654
- [x] https://github.com/osquery/osquery/pull/7629
- [x] https://github.com/osquery/osquery/pull/7628

**Comment by mike-myers-tob** [comment]
In addition to the above backlogged tasks, we need to address the following in 5.5:

- [ ] https://github.com/osquery/osquery/issues/7719

**Comment by mike-myers-tob** [comment]
And now for 5.6, if not sooner in a point release:

- [ ] https://github.com/osquery/osquery/pull/7736

**Comment by mike-myers-tob** [comment]
For 5.6:

- [ ] https://github.com/osquery/osquery/issues/7720

**Comment by directionless** [comment]
I think this will be closed by https://github.com/osquery/osquery/issues/7690

**Comment by mike-myers-tob** [comment]
Closing this in favor of the new automated CVE tracker that is opening issues (sort by the label:`libraries`)
