### ISSUE TITLE
CPU utilization % per process 

### ISSUE THREAD

**Issue by shoenig** [facebook/osquery#757]
Maybe I'm missing something, but it would be nice to have the equivalent of %CPU that top has per process. This could be useful for finding load spikes and heavily loaded machines.

**Comment by theopolis** [comment]
Great question! To get the utilization you'll have to sample the relative CPU time for each process in user and kernel land. Then compare (ratio) that to wall time.

Here's an example of how we do it within osquery: https://github.com/facebook/osquery/blob/master/osquery/core/watcher.cpp#L104

But it's hard to expose that as a column since we'd need wall time to sample. We're thinking of ways to represent this as latent or performance-impacting processes. Imagine a "`select * from process_performance`". To expose something like utilization we might be able to keep a small cache in RocksDB of times when the shell/daemon starts, then report relative user/system times.

**Comment by theopolis** [comment]
I've recorded performance on the virtual tables roadmap: https://github.com/facebook/osquery/issues/619

Thanks @shoenig!
