### ISSUE TITLE
startup_items OSX only using .plist

### ISSUE THREAD

**Issue by mag00** [facebook/osquery#758]
It looks as if startup_items is not populating the path on OSX:

```
+----------+------+------------+-------------------------------------------------------------+
| name     | path | type       | source                                                      |
+----------+------+------------+-------------------------------------------------------------+
| Dropbox  |      | Login Item | /Users/magoo/Library/Preferences/com.apple.loginitems.plist |
| DDAssist |      | Login Item | /Users/magoo/Library/Preferences/com.apple.loginitems.plist |
| Chess    |      | Login Item | /Users/magoo/Library/Preferences/com.apple.loginitems.plist |
+----------+------+------------+-------------------------------------------------------------+
```

This seems to be causing an odd behavior, when any new startup item has been added or removed to this table, osquery seems to think they've all been removed and added again. The .plist hash changes on additions / removals which may falsely indicate that all the items have changed. 

A better behavior may be to populate the path column and observe changes to each individual executable? Currently 5 logs are created for any one startup addition (remove dropbox, add dropbox, remove dd assist, add ddassist, add chess)

**Comment by jedi22** [comment]
Are you running this with osqueryi and user permissions? (not root)

**Comment by mag00** [comment]
osqueryi gave me that output, but osqueryd logs reflect the behavior I described. not root.

**Comment by theopolis** [comment]
This was auto-closed since the PR included [Fix...] but that PR just added path/alias parsing. I tested a few times trying to log the differentials and it appears that is working fine.

How I tested:
1. Start osqueryd --verbose_debug
2. Check that the entire startup_items table is dumped to /var/osquery/osqueryd.results.log
3. Add a startup item for my user using the pref panel
4. Check that ONLY the addition was logged to results.log (via the debugging message osqueryd spits to stderr, and the JSON event line).

@mag00, if the results differentials are still including the whole startup_items table when anything changes let me know and we'll reopen/investigate.
