### ISSUE TITLE
Using osquery from the browser

### ISSUE THREAD

**Issue by mansu** [facebook/osquery#764]
I am planning to put a browser based interface on top of osquery. Does osquery expose a thrift or http end point I can query? Even aA JDBC/ODBC end point or a qay to query the sqlite db  from node.js would do.

osqueryd doesn't seem to expose an endpoint and  the osquery.thrift file doesn't seem to do what I want and I found no other thrift services in the repo.

**Comment by marpaia** [comment]
Every table is an extension, so you could "call" the registry item for the table you were trying to query with a serialized QueryContext in your ExtensionPluginRequest, but that would be a pain. We can probably add a `Query` endpoint or something pretty easily. I'm assuming something where you pass in a query string and get back a serialized `osquery::QueryData` would be sufficient?

**Comment by theopolis** [comment]
Here's an example of calling the registry to get `TableData`: https://github.com/facebook/osquery/blob/master/osquery/sql/sql.cpp#L59. There's minimal SQL parsing/planning when using the registry directly as the registry handles Tables, Flags, EventPublishers, ConfigPlugins, LoggerPlugins. The `RegistryFactory` API is exposed via Thrift using extensions: https://github.com/facebook/osquery/blob/master/osquery/extensions/extensions_tests.cpp#L233.

But what you're looking for will be included as a DistributedQueryHandler https://github.com/facebook/osquery/blob/master/osquery/distributed/distributed.h#L119

The handler concept is dedicated to SQL, it will combine the extensions (current Thrift API) and registry to handle SQL lexing, parsing, planning, etc using SQLite. This "query handler" concept is broken out from registry and extensions as the registry handles internal 'routing', extensions handle machine-local 'routing' using a domain socket, and now a "query handler" will handle remote/distributed 'routing'. And that remote/distributed control will be limited to SQL. For network/remote/distributed config management or log aggregation the best place to write code is as a Config/LoggerPlugin.

We'll have authentication built into the DistributedQueryHandler too, supporting a TLS-clientauth or shared secret deployment key + enrollment secret (similar to Chef) soon. Then web services, like the one you mention, can implement the authorization. :)

**Comment by mansu** [comment]
@marpaia Thanks for the response. Yes, that is exactly what I am looking for. Is all the objects are thrift objects, that I can generate a JS client for the code and consume it in my app. 

PS: Sorry for the late response. Just saw this notification.

**Comment by mansu** [comment]
@theopolis Yes, the code you pointed out is what I need to be wrapped. From your description it looks like adding the thrift call is a long way out. Can it be prioritized sooner? For some context, I am working on implementing a shell for linux newbies on top of osquery.

**Comment by theopolis** [comment]
Sure, I can prioritize! I need to look into the Apache Thrift SSLSocketFactory API since I'm only familiar with the Facebook internal version (version 2 so to speak). If I can't get TLS clientauth and some form of TLS server CA/certificate pinning then we'll have to use the openssl libs and expose a JSON-based REST API.

The model will most likely entail a basic two step:
1. The osqueryd will be configured with a server hostname, optional x509 AKID, or optional deployment shared secret (called an enrollment-key).
2. The osqueryd "client" will make polling periodic requests to the server for actions/queries to run and return results.

So imagine a server must implement:
`GET /api/v1/ping`
Ping returns basic information about the server including the supported authentication type.
Return: `version`: Simple SDK-conforming version ID. `auth_type`: TLS-clientauth or enrollment-key
`POST /api/v1/enroll`
`host_id`: The configured osqueryd host identifier (you can use a machine uuid/hostname).
`enrollment_key`: (Optional) if using enrollment shared-secret authentication.
`version`: The SDK-conforming version osqueryd was compiled with.
I'm sure there's more information the clients will submit when enrolling. If using TLS-clientauth the server checks checks that the trust chain for it's certificate matches the client certification. The server can optionally require the client's TLS certificate's CN to match the hostname (rDNS) the client connected with. If using an enrollment key the server simply checks that the enrollment key matches.
Return: `status`: success/failure. `node_key`: (Optional) if using an enrollment-key authentication the client must use a supplemental `node_key` for future requests. This is generated, stored, and given to the client after successful enrollment.
`GET /api/v1/poll` (definitely up for suggestions on a better endpoint name here)
`node_key`: (Optional) if using an enrollment-key authentication.
`host_id`: The configured osqueryd host identifier.
This really only needs the `node_key` for authentication and identification, the `host_id` is supplemental and nice to track for changes. If the server is authenticating with TLS-clientauth then the identification/lookup is performed on the TLS certificate's SKID or hash. 
`PUT /api/v1/results`
`results`: The osquery `QueryData` JSON-serialized row data.
The first version might only support async requests from the server. The thought here is: returning the query results back to the server will be optional. By default the results will go to the configured `LoggerPlugin` but the server or client and set to return them to some endpoint. I have to think more about this and what the default option should be, it might be a required option on the client: `allow_distributed_results_response`.

The TLS-client authentication provides a few extra options when using the optional pinning features but most folks will use the enrollment-key option. It'll be easier to deploy a protected file containing a shared secret to your enterprise or set of hosts running osqueryd. :)

The server that osqueryd clients connect to MUST use TLS-serverauth. By default, when using this sort of "distributed" quering, the clients will choose to fail their own enrollment if TLS fails. This is to prevent rouge servers from quering your set of osqueryd hosts. As soon as I figure out of I can get this control + optional pinning on the TLS server's CA/certificate we can publish the exact API and implement the client code/example server code.

**Comment by theopolis** [comment]
Hey @mansu, for clarification, do you want to run the webserver on the same host as osqueryd? If so then there's no need for osqueryd (node/client) to a server communication via TLS/HTTP. We can extend the local UNIX domain socket extension API to allow queries. Then as long as the webserver's user/group can read/write to the domain socket, you'll be gtg. And of course you'll still need to lock down access to the web UI.

**Comment by theopolis** [comment]
If you're looking for local communication then this PR will add the `query` endpoing to the thrift extensions API: https://github.com/facebook/osquery/pull/771

**Comment by mansu** [comment]
@theopolis Yes a local domain socket will totally work for my use case. Thanks for adding the query API. Since it looks like it's merged into master is the API to go or is there any more follow up work?

**Comment by theopolis** [comment]
No problem! You're welcome to stack hacking away on it, it passes the **single** unit test: [extensions_tests.cpp#L188](https://github.com/facebook/osquery/blob/master/osquery/extensions/extensions_tests.cpp#L188).

I'm going to write some integration tests tonight+tomorrow for the entire extensions API but that will only include the cpp/thrift-code we have in: [extensions.cpp](https://github.com/facebook/osquery/blob/master/osquery/extensions/extensions.cpp) which are all using the cpp Thrift lib (mainly the [TSocket transport](https://git-wip-us.apache.org/repos/asf?p=thrift.git;a=blob;f=lib/cpp/src/thrift/transport/TSocket.cpp;h=ea85bfb4d04d9d9e20b613420286dcf48a4bed19;hb=HEAD))

I know there's an equivalent [TSocket for python](https://git-wip-us.apache.org/repos/asf?p=thrift.git;a=blob;f=lib/py/src/transport/TSocket.py;h=0175bdc4958d3c1e46d00502af21db8cae6b401d;hb=HEAD) that uses domain sockets . I don't see one for node.js :(

**Comment by mansu** [comment]
Thanks! Python also works. Please feel free to resolve this once you think you are done. I will play with this over the weekend and let you know how it goes.

**Comment by theopolis** [comment]
Awesome, let me know how it goes, and if you need any additional APIs.
