### ISSUE TITLE
Clear performance stats when modifying scheduled query

### ISSUE THREAD

**Issue by getvictor** [facebook/osquery#8209]
# Feature request

### What new feature do you want?

When I modify the query in my schedule (but the name remains the same), I want the the old stats from the previous query to be cleared, since the actual query is now different. Example new config:
```
    "packs": {
        "Global": {
            "queries": {
                "Get JetBrains Plugins": {
                    "query": "select * from time;",
                    "interval": 3600,
                    "platform": "",
                    "version": "",
                    "snapshot": true
                }
            }
        },
```

### How is this new feature useful?

This will keep the performance statistics accurate.

### How can this be implemented?

Do it in the config update function by comparing old vs new query strings.

**Comment by directionless** [comment]
I'm not opposed.

But I think there's a related issue -- osquery seems to assume that the sql is immutable. We see this here, but we also see in how the result counter and diffs come in. If you change the SQL, but not the name, the counter doesn't reset, and the diffs continue. (Which is confusing)

Which is a long winded way of saying I'd accept a PR for this, and that osquery is really confusing.

**Comment by bgirardeau-figma** [comment]
> But I think there's a related issue -- osquery seems to assume that the sql is immutable. We see this here, but we also see in how the result counter and diffs come in. If you change the SQL, but not the name, the counter doesn't reset, and the diffs continue. (Which is confusing)

For the diff state and counter, I like the current approach because a change to the SQL may not meaningfully change the semantic meaning of the results. If I make an addition to a list of exclusion/inclusion conditions or refactor a complex query to be more performant, I'd rather not reset the diff. Using the query name as the boundary gives the user control over what they consider a "different" query for that purpose.

I'm not sure if the same argument/preference applies to performance stats though, I could imagine those being useful to tie more closely to the actual SQL (would want to think more about specific stats). Maybe having a new concept of SQL "version" for a given named query in the code/stats would help in some way.
