### ISSUE TITLE
[Feature Request] tab completion in osqueryi

### ISSUE THREAD

**Issue by rmetzler** [facebook/osquery#826]
Writing SQL queries is a pretty repetitive task, so I think `osqueryi` would improve with auto completion.

**Comment by van7hu** [comment]
Personally, I think this feature is quite good to implement.

On 6 March 2015 at 02:50, Richard Metzler <notifications@github.com> wrote:

> Writing SQL queries is a pretty repetitive task, so I think osqueryi
> would improve with auto completion.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/facebook/osquery/issues/826>.
>



-- 
Best regards,
van7hu

**Comment by theopolis** [comment]
The osqueryi shell is a slightly modified version of the SQLite-bundled shell. It uses readline (if available) for most of the history/repl interaction. A tab-completion feature similar to this [GNU tab-auto-complete](http://cc.byexamples.com/2008/06/16/gnu-readline-implement-custom-auto-complete/) readline tutorial could be doable. 

The auto complete generator would have to tokenize the characters slightly, for `table.column` and read-behind for instances like `SELECT (column|tablename.column)`. The SQLite [grammar](https://www.sqlite.org/lang.html) is a bit large and there are quite a few instances where tablename or columns could be used. One could also auto-complete using a dictionary of all table names and all columns and let the queryer pick. Rather than trying to down-select for them to table name OR column depending on the WIP statement.

If anyone is interested in adding this feature the set of table names:
```cpp
std::vector<std::string> tables = Registry::names("table");
```

And for columns, check [this example](https://github.com/facebook/osquery/blob/master/osquery/sql/virtual_table.cpp#L280) where both the table names and column name/type for each is iterated.

**Comment by marpaia** [comment]
This is a really good idea, but it's apart of a larger effort that we need to take on. I made a master task for this effort in #973 so that we can track the progress of these issues and discuss them there.

Closing this for now.
