### ISSUE TITLE
path formatting in JSON output

### ISSUE THREAD

**Issue by keeleysam** [facebook/osquery#877]
Currently in the JSON output paths have \\\ added before /, which results in ugly output.  These should be removed when converting to JSON.

Example:
```
{"name":"processes_netconn","hostIdentifier":"mbp.keeleysam.com","calendarTime":"Wed Mar 18 04:26:20 2015","unixTime":"1426677980","columns":{"cmdline":"\\u0001 \\\/Applications\\\/Safari.app\\\/Contents\\\/MacOS\\\/Safari","local_address":"172.16.0.12","local_port":"64518","name":"Safari","on_disk":"1","parent":"1","path":"\\\/Applications\\\/Safari.app\\\/Contents\\\/MacOS\\\/Safari","pid":"26755","remote_address":"74.125.224.100","remote_port":"443","start_time":"343643044339550","uid":"501"},"action":"added"}
```

**Comment by jedi22** [comment]
So this is a problem caused by two separate calls to write_json.

This problem start in launchQuery in scheduler.cpp.

On line 85 we call `dbQuery.addNewResults`, which eventually ends up in query.cpp on line 114, where we serialize the data for the first time into JSON (LN202 : results.cpp), we then finish that and back out to launchQuery again at which point we continue on to line 118 where we call `logSecheduledQueryLogItem` which calls `serializeScheduledQueryLogItemJSON` which will serialize the data again, ending up with gratuitous slashes.

Concisely, here is the call chain:
```C++
launchQuery
   dbQuery.addNewResults
        serializeHistoricalQueryResultsJSON
            write_json
logScheduledQueryItem
    serializeScheduledQueryLogItemJSON
        write_json
```

We need to eliminate one of these

**Comment by eastebry** [comment]
IIRC: This double-escape was a quick, ugly fix for #520.

Until the upstream issue is fixed, we might want to consider replacing [this call](https://github.com/facebook/osquery/blob/master/osquery/database/results.cpp#L39) with a custom function that escapes non-ascii characters, but leaves slashes alone.

**Comment by jedi22** [comment]
Yeah, that's my current plan :)

**Comment by jedi22** [comment]
This will continue to be tracked in the pull request.
